
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "VSTHRD109:Switch instead of assert in async methods", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.VisualStudio.R.Package.DataInspect.Office.CsvAppFileIO.OpenDataCsvAppAsync(Microsoft.R.DataInspection.IREvaluationResultInfo,Microsoft.Common.Core.Shell.ICoreShell,Microsoft.Common.Core.IO.IFileSystem,Microsoft.Common.Core.OS.IProcessServices)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.VisualStudio.R.Package.ProjectSystem.PropertyPages.PropertyPageViewModel.Initialize~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.VisualStudio.R.Package.ProjectSystem.PropertyPages.PropertyPage.OnDeactivate~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "VSTHRD109:Switch instead of assert in async methods", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.VisualStudio.R.Package.Sql.Publish.SqlPublishOptionsDialogViewModel.PopulateTargetsAsync~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "VSSDK006:Check services exist", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.VisualStudio.R.Package.Packages.BasePackage`1.AdviseExportedWindowFrameEvents``1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "VSTHRD108:Assert thread affinity unconditionally", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.VisualStudio.R.Package.Logging.OutputWindowLogWriter.EnsurePaneVisible")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.VisualStudio.R.Package.ProjectSystem.PropertyPages.PropertyPage.OnApply~System.Threading.Tasks.Task{System.Int32}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "VSSDK006:Check services exist", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.VisualStudio.R.Package.Packages.BasePackage`1.AdviseExportedDebuggerEvents``1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "VSTHRD109:Switch instead of assert in async methods", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.VisualStudio.R.Package.StatusBar.VsStatusBar.GetTextAsync(System.Threading.CancellationToken)~System.Threading.Tasks.Task{System.String}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "VSTHRD109:Switch instead of assert in async methods", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.VisualStudio.R.Package.StatusBar.VsStatusBar.SetTextAsync(System.String,System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "VSTHRD109:Switch instead of assert in async methods", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.VisualStudio.R.Package.DataInspect.Viewers.GridViewerBase.ViewAsync(System.String,System.String,System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "VSTHRD108:Assert thread affinity unconditionally", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.VisualStudio.R.Package.DataInspect.Viewers.GridViewerBase.ViewAsync(System.String,System.String,System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "VSTHRD108:Assert thread affinity unconditionally", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.VisualStudio.R.Package.Shell.VisualComponentToolWindowAdapter`1.Show(System.Boolean,System.Boolean)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "VSTHRD010:Invoke single-threaded types on Main thread", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.VisualStudio.R.Package.Logging.OutputWindowLogWriter.Write(Microsoft.Common.Core.Logging.MessageCategory,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "VSTHRD108:Assert thread affinity unconditionally", Justification = "<Pending>", Scope = "member", Target = "~P:Microsoft.VisualStudio.R.Package.ProjectSystem.PropertyPages.PropertyPage.IsDirty")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "VSTHRD109:Switch instead of assert in async methods", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.VisualStudio.R.Package.ProjectSystem.OpenRDataVsUiHierarchyWindowCommandGroupHandler.TryHandleCommandAsyncInternalAsync(Microsoft.VisualStudio.ProjectSystem.IProjectTree)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "VSTHRD108:Assert thread affinity unconditionally", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.VisualStudio.R.Package.Utilities.ToolWindowUtilities.ShowToolWindow(Microsoft.VisualStudio.Shell.ToolWindowPane,Microsoft.Common.Core.Threading.IMainThread,System.Boolean,System.Boolean)")]

