//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.VisualStudio.R.Package {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.VisualStudio.R.Package.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string AdvancedEditorOptions {
            get {
                return ResourceManager.GetString("AdvancedEditorOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Language Editor.
        /// </summary>
        internal static string EditorName {
            get {
                return ResourceManager.GetString("EditorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.
        /// </summary>
        internal static string LanguageName {
            get {
                return ResourceManager.GetString("LanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Interactive.
        /// </summary>
        internal static string ReplWindowName {
            get {
                return ResourceManager.GetString("ReplWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Language Files (*.r)|*.r|All Files (*.*)|*.*.
        /// </summary>
        internal static string SaveAsFilterR {
            get {
                return ResourceManager.GetString("SaveAsFilterR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic formatting.
        /// </summary>
        internal static string Settings_AutoFormat {
            get {
                return ResourceManager.GetString("Settings_AutoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reformat code as you type.
        /// </summary>
        internal static string Settings_AutoFormat_Description {
            get {
                return ResourceManager.GetString("Settings_AutoFormat_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compact.
        /// </summary>
        internal static string Settings_BracePositionCompact {
            get {
                return ResourceManager.GetString("Settings_BracePositionCompact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expanded.
        /// </summary>
        internal static string Settings_BracePositionExpanded {
            get {
                return ResourceManager.GetString("Settings_BracePositionExpanded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semi-expanded.
        /// </summary>
        internal static string Settings_BracePositionSemiExpanded {
            get {
                return ResourceManager.GetString("Settings_BracePositionSemiExpanded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brace positions.
        /// </summary>
        internal static string Settings_BracePositionStyle {
            get {
                return ResourceManager.GetString("Settings_BracePositionStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines curly brace positions during formatting.
        /// </summary>
        internal static string Settings_BracePositionStyle_Description {
            get {
                return ResourceManager.GetString("Settings_BracePositionStyle_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit on space key.
        /// </summary>
        internal static string Settings_CommitOnSpace {
            get {
                return ResourceManager.GetString("Settings_CommitOnSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit intellisense selection when space key is pressed.
        /// </summary>
        internal static string Settings_CommitOnSpace_Description {
            get {
                return ResourceManager.GetString("Settings_CommitOnSpace_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completion.
        /// </summary>
        internal static string Settings_CompletionCategory {
            get {
                return ResourceManager.GetString("Settings_CompletionCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable validation.
        /// </summary>
        internal static string Settings_EnableValidation {
            get {
                return ResourceManager.GetString("Settings_EnableValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable document validation and syntax checking.
        /// </summary>
        internal static string Settings_EnableValidation_Description {
            get {
                return ResourceManager.GetString("Settings_EnableValidation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format on paste.
        /// </summary>
        internal static string Settings_FormatOnPaste {
            get {
                return ResourceManager.GetString("Settings_FormatOnPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically format and indent HTML fragment on paste.
        /// </summary>
        internal static string Settings_FormatOnPaste_Description {
            get {
                return ResourceManager.GetString("Settings_FormatOnPaste_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatting.
        /// </summary>
        internal static string Settings_FormattingCategory {
            get {
                return ResourceManager.GetString("Settings_FormattingCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IntelliSense.
        /// </summary>
        internal static string Settings_IntellisenseCategory {
            get {
                return ResourceManager.GetString("Settings_IntellisenseCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string Settings_PasteCategory {
            get {
                return ResourceManager.GetString("Settings_PasteCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show internal functions.
        /// </summary>
        internal static string Settings_ShowInternalFunctions {
            get {
                return ResourceManager.GetString("Settings_ShowInternalFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show internal functions (functions beginning with dot) in the statement completion list.
        /// </summary>
        internal static string Settings_ShowInternalFunctions_Description {
            get {
                return ResourceManager.GetString("Settings_ShowInternalFunctions_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show TCL functions.
        /// </summary>
        internal static string Settings_ShowTclFunctions {
            get {
                return ResourceManager.GetString("Settings_ShowTclFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show functions from TCL/TK package in the statement completion list.
        /// </summary>
        internal static string Settings_ShowTclFunctions_Description {
            get {
                return ResourceManager.GetString("Settings_ShowTclFunctions_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space after comma.
        /// </summary>
        internal static string Settings_SpaceAfterComma {
            get {
                return ResourceManager.GetString("Settings_SpaceAfterComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert space after comma in function arguments.
        /// </summary>
        internal static string Settings_SpaceAfterComma_Description {
            get {
                return ResourceManager.GetString("Settings_SpaceAfterComma_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space after keyword.
        /// </summary>
        internal static string Settings_SpaceAfterKeyword {
            get {
                return ResourceManager.GetString("Settings_SpaceAfterKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert space after keyword and before opening brace such as in case of &apos;if&apos;, &apos;while&apos;, &apos;repeat&apos;.
        /// </summary>
        internal static string Settings_SpaceAfterKeyword_Description {
            get {
                return ResourceManager.GetString("Settings_SpaceAfterKeyword_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting description.
        /// </summary>
        internal static string Temp_SettingDescription {
            get {
                return ResourceManager.GetString("Temp_SettingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        internal static string Temp_SettingDisplayName {
            get {
                return ResourceManager.GetString("Temp_SettingDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format Document.
        /// </summary>
        internal static string UndoActionFormatDocument {
            get {
                return ResourceManager.GetString("UndoActionFormatDocument", resourceCulture);
            }
        }
    }
}
