//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.VisualStudio.R.Package {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.VisualStudio.R.Package.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string AdvancedEditorOptions {
            get {
                return ResourceManager.GetString("AdvancedEditorOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open plot file. Exception: {0}.
        /// </summary>
        internal static string CannotOpenPlotFile {
            get {
                return ResourceManager.GetString("CannotOpenPlotFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control+E, Control+E.
        /// </summary>
        internal static string CtrlECtrlE {
            get {
                return ResourceManager.GetString("CtrlECtrlE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control+Enter.
        /// </summary>
        internal static string CtrlEnter {
            get {
                return ResourceManager.GetString("CtrlEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Language Editor.
        /// </summary>
        internal static string EditorName {
            get {
                return ResourceManager.GetString("EditorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please open a saved plot file to display data.
        /// </summary>
        internal static string EmptyPlotWindowWatermark {
            get {
                return ResourceManager.GetString("EmptyPlotWindowWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete file {0}. Exception: {1}..
        /// </summary>
        internal static string Error_CannotDeleteFile {
            get {
                return ResourceManager.GetString("Error_CannotDeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown conversion failed.
        /// </summary>
        internal static string Error_MarkdownConversionFailed {
            get {
                return ResourceManager.GetString("Error_MarkdownConversionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.R.Host.exe is missing. Click OK to open download link in the default browser..
        /// </summary>
        internal static string Error_Microsoft_R_Host_Missing {
            get {
                return ResourceManager.GetString("Error_Microsoft_R_Host_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation requires package {0} which is not installed or has been removed. .
        /// </summary>
        internal static string Error_PackageMissing {
            get {
                return ResourceManager.GetString("Error_PackageMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input is too long - no more than {0} characters expected..
        /// </summary>
        internal static string InputIsTooLong {
            get {
                return ResourceManager.GetString("InputIsTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.
        /// </summary>
        internal static string LanguageName {
            get {
                return ResourceManager.GetString("LanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Host process is stopped. Click Reset to start a new one..
        /// </summary>
        internal static string MicrosoftRHostStopped {
            get {
                return ResourceManager.GetString("MicrosoftRHostStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping R Host process....
        /// </summary>
        internal static string MicrosoftRHostStopping {
            get {
                return ResourceManager.GetString("MicrosoftRHostStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open R Plot File.
        /// </summary>
        internal static string OpenPlotDialogTitle {
            get {
                return ResourceManager.GetString("OpenPlotDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Packages.
        /// </summary>
        internal static string OutputWindowName_InstallPackages {
            get {
                return ResourceManager.GetString("OutputWindowName_InstallPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Publish.
        /// </summary>
        internal static string OutputWindowName_Publish {
            get {
                return ResourceManager.GetString("OutputWindowName_Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Plot Files (*.vsplot)|*.vsplot|All Files (*.*)|*.*.
        /// </summary>
        internal static string PlotFileFilter {
            get {
                return ResourceManager.GetString("PlotFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Plot.
        /// </summary>
        internal static string PlotWindowCaption {
            get {
                return ResourceManager.GetString("PlotWindowCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Interactive.
        /// </summary>
        internal static string ReplWindowName {
            get {
                return ResourceManager.GetString("ReplWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown Files (*.md;*.rmd;*.markdown)|*.md;*.rmd;*.markdown|All Files (*.*)|*.*.
        /// </summary>
        internal static string SaveAsFilterMD {
            get {
                return ResourceManager.GetString("SaveAsFilterMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Language Files (*.r)|*.r|All Files (*.*)|*.*.
        /// </summary>
        internal static string SaveAsFilterR {
            get {
                return ResourceManager.GetString("SaveAsFilterR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic formatting.
        /// </summary>
        internal static string Settings_AutoFormat {
            get {
                return ResourceManager.GetString("Settings_AutoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reformat code as you type.
        /// </summary>
        internal static string Settings_AutoFormat_Description {
            get {
                return ResourceManager.GetString("Settings_AutoFormat_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expanded braces.
        /// </summary>
        internal static string Settings_BracesExpanded {
            get {
                return ResourceManager.GetString("Settings_BracesExpanded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place open curly brace on a new line.
        /// </summary>
        internal static string Settings_BracesExpanded_Description {
            get {
                return ResourceManager.GetString("Settings_BracesExpanded_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit on space key.
        /// </summary>
        internal static string Settings_CommitOnSpace {
            get {
                return ResourceManager.GetString("Settings_CommitOnSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit intellisense selection when space key is pressed.
        /// </summary>
        internal static string Settings_CommitOnSpace_Description {
            get {
                return ResourceManager.GetString("Settings_CommitOnSpace_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completion.
        /// </summary>
        internal static string Settings_CompletionCategory {
            get {
                return ResourceManager.GetString("Settings_CompletionCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show syntax errors.
        /// </summary>
        internal static string Settings_EnableSyntaxCheck {
            get {
                return ResourceManager.GetString("Settings_EnableSyntaxCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable automatic syntax checking in the code.
        /// </summary>
        internal static string Settings_EnableSyntaxCheck_Description {
            get {
                return ResourceManager.GetString("Settings_EnableSyntaxCheck_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format on paste.
        /// </summary>
        internal static string Settings_FormatOnPaste {
            get {
                return ResourceManager.GetString("Settings_FormatOnPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically format and indent code fragment on paste.
        /// </summary>
        internal static string Settings_FormatOnPaste_Description {
            get {
                return ResourceManager.GetString("Settings_FormatOnPaste_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatting.
        /// </summary>
        internal static string Settings_FormattingCategory {
            get {
                return ResourceManager.GetString("Settings_FormattingCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IntelliSense.
        /// </summary>
        internal static string Settings_IntellisenseCategory {
            get {
                return ResourceManager.GetString("Settings_IntellisenseCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interactive window.
        /// </summary>
        internal static string Settings_ReplCategory {
            get {
                return ResourceManager.GetString("Settings_ReplCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax check in R Console.
        /// </summary>
        internal static string Settings_ReplSyntaxCheck {
            get {
                return ResourceManager.GetString("Settings_ReplSyntaxCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turns on or off live code syntax check in R Console window. Syntax check may not work correctly in multi-line statements..
        /// </summary>
        internal static string Settings_ReplSyntaxCheck_Description {
            get {
                return ResourceManager.GetString("Settings_ReplSyntaxCheck_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Send to R Console&apos; shortcut.
        /// </summary>
        internal static string Settings_SendToRepl {
            get {
                return ResourceManager.GetString("Settings_SendToRepl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override editor &apos;insert empty line above&apos; command and use Control+Enter for sending editor selection to R Console instead. Keyboard bindings can also be change in Tools &gt; Options &gt; Environment &gt; Keyboard..
        /// </summary>
        internal static string Settings_SendToRepl_Description {
            get {
                return ResourceManager.GetString("Settings_SendToRepl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show internal functions.
        /// </summary>
        internal static string Settings_ShowInternalFunctions {
            get {
                return ResourceManager.GetString("Settings_ShowInternalFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show internal functions (functions beginning with dot) in the statement completion list.
        /// </summary>
        internal static string Settings_ShowInternalFunctions_Description {
            get {
                return ResourceManager.GetString("Settings_ShowInternalFunctions_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show TCL functions.
        /// </summary>
        internal static string Settings_ShowTclFunctions {
            get {
                return ResourceManager.GetString("Settings_ShowTclFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show functions from TCL/TK package in the statement completion list.
        /// </summary>
        internal static string Settings_ShowTclFunctions_Description {
            get {
                return ResourceManager.GetString("Settings_ShowTclFunctions_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space after comma.
        /// </summary>
        internal static string Settings_SpaceAfterComma {
            get {
                return ResourceManager.GetString("Settings_SpaceAfterComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert space after comma in function arguments.
        /// </summary>
        internal static string Settings_SpaceAfterComma_Description {
            get {
                return ResourceManager.GetString("Settings_SpaceAfterComma_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space after keyword.
        /// </summary>
        internal static string Settings_SpaceAfterKeyword {
            get {
                return ResourceManager.GetString("Settings_SpaceAfterKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert space after keyword and before opening brace such as in case of &apos;if&apos;, &apos;while&apos;, &apos;repeat&apos;.
        /// </summary>
        internal static string Settings_SpaceAfterKeyword_Description {
            get {
                return ResourceManager.GetString("Settings_SpaceAfterKeyword_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax check.
        /// </summary>
        internal static string Settings_SyntaxCheckCategory {
            get {
                return ResourceManager.GetString("Settings_SyntaxCheckCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting description.
        /// </summary>
        internal static string Temp_SettingDescription {
            get {
                return ResourceManager.GetString("Temp_SettingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        internal static string Temp_SettingDisplayName {
            get {
                return ResourceManager.GetString("Temp_SettingDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format Document.
        /// </summary>
        internal static string UndoActionFormatDocument {
            get {
                return ResourceManager.GetString("UndoActionFormatDocument", resourceCulture);
            }
        }
    }
}
