//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.VisualStudio.R.Package {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.VisualStudio.R.Package.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string AdvancedEditorOptions {
            get {
                return ResourceManager.GetString("AdvancedEditorOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask.
        /// </summary>
        public static string Ask {
            get {
                return ResourceManager.GetString("Ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive with log files exceeds {0} MB. Sending large file as an attachment may not be possible..
        /// </summary>
        public static string AttachmentTooLarge1 {
            get {
                return ResourceManager.GetString("AttachmentTooLarge1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please place archived files on a file share and add link to the e-mail. When you click OK, Visual Studio will open TEMP folder in the Windows Explorer..
        /// </summary>
        public static string AttachmentTooLarge2 {
            get {
                return ResourceManager.GetString("AttachmentTooLarge2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archived logs are in {0} file that can be found in {1}.
        /// </summary>
        public static string AttachmentTooLarge3 {
            get {
                return ResourceManager.GetString("AttachmentTooLarge3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Automatic&gt;.
        /// </summary>
        public static string AutomaticValue {
            get {
                return ResourceManager.GetString("AutomaticValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External.
        /// </summary>
        public static string BrowserType_External {
            get {
                return ResourceManager.GetString("BrowserType_External", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal.
        /// </summary>
        public static string BrowserType_Internal {
            get {
                return ResourceManager.GetString("BrowserType_Internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Directory.
        /// </summary>
        public static string ChooseDirectory {
            get {
                return ResourceManager.GetString("ChooseDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose R Install Folder.
        /// </summary>
        public static string ChooseRInstallFolder {
            get {
                return ResourceManager.GetString("ChooseRInstallFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collecting OS information.
        /// </summary>
        public static string CollectingOSInformation {
            get {
                return ResourceManager.GetString("CollectingOSInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collecting R Tools for Visual Studio logs.
        /// </summary>
        public static string CollectingRTVSLogs {
            get {
                return ResourceManager.GetString("CollectingRTVSLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collecting events from system log.
        /// </summary>
        public static string CollectingSystemEvents {
            get {
                return ResourceManager.GetString("CollectingSystemEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting....
        /// </summary>
        public static string Converting {
            get {
                return ResourceManager.GetString("Converting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Use .Rprofile).
        /// </summary>
        public static string CranMirror_UseRProfile {
            get {
                return ResourceManager.GetString("CranMirror_UseRProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to download CRAN mirror list. The request has been canceled..
        /// </summary>
        public static string CranMirrorListRequestCanceled {
            get {
                return ResourceManager.GetString("CranMirrorListRequestCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating ZIP archive.
        /// </summary>
        public static string CreatingArchive {
            get {
                return ResourceManager.GetString("CreatingArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV (*.csv;*.txt)|*.csv;*.txt|All Files (*.*)|*.*.
        /// </summary>
        public static string CsvFileFilter {
            get {
                return ResourceManager.GetString("CsvFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control+E, Control+E.
        /// </summary>
        public static string CtrlECtrlE {
            get {
                return ResourceManager.GetString("CtrlECtrlE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control+Enter.
        /// </summary>
        public static string CtrlEnter {
            get {
                return ResourceManager.GetString("CtrlEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove all history entries?.
        /// </summary>
        public static string DeleteAllHistoryEntries {
            get {
                return ResourceManager.GetString("DeleteAllHistoryEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the selected entries from the history?.
        /// </summary>
        public static string DeleteSelectedHistoryEntries {
            get {
                return ResourceManager.GetString("DeleteSelectedHistoryEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Microsoft R Client setup application....
        /// </summary>
        public static string DownloadingRClientInstaller {
            get {
                return ResourceManager.GetString("DownloadingRClientInstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Language Editor.
        /// </summary>
        public static string EditorName {
            get {
                return ResourceManager.GetString("EditorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to collect and package logs. Exception: {0}.
        /// </summary>
        public static string Error_CannotCollectLogs {
            get {
                return ResourceManager.GetString("Error_CannotCollectLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete file {0}. Exception: {1}..
        /// </summary>
        public static string Error_CannotDeleteFile {
            get {
                return ResourceManager.GetString("Error_CannotDeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open CSV file. Exception: {0}..
        /// </summary>
        public static string Error_CannotOpenCsv {
            get {
                return ResourceManager.GetString("Error_CannotOpenCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error sending e-mail: {0} ({1})..
        /// </summary>
        public static string Error_CannotSendFeedback1 {
            get {
                return ResourceManager.GetString("Error_CannotSendFeedback1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please compose and send e-mail manually to rtvscore@microsoft.com. If possible, attach {0} file that can be found in {1}..
        /// </summary>
        public static string Error_CannotSendFeedback2 {
            get {
                return ResourceManager.GetString("Error_CannotSendFeedback2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to access path {0}. Exception: {1}..
        /// </summary>
        public static string Error_ExceptionAccessingPath {
            get {
                return ResourceManager.GetString("Error_ExceptionAccessingPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown conversion failed.
        /// </summary>
        public static string Error_MarkdownConversionFailed {
            get {
                return ResourceManager.GetString("Error_MarkdownConversionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.R.Host.exe is missing. Please reinstall or repair R Tools for Visual Studio..
        /// </summary>
        public static string Error_Microsoft_R_Host_Missing {
            get {
                return ResourceManager.GetString("Error_Microsoft_R_Host_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation requires package {0} which is not installed or has been removed. .
        /// </summary>
        public static string Error_PackageMissing {
            get {
                return ResourceManager.GetString("Error_PackageMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing markdown requires Pandoc. Please install Pandoc for Windows from http://pandoc.org/installing.html. Click OK to open the Pandoc download page in default browser. You may need to restart Visual Studio when the Pandoc setup completes..
        /// </summary>
        public static string Error_PandocMissing {
            get {
                return ResourceManager.GetString("Error_PandocMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing markdown to PDF requires TeX installation. Please install MiKTeX (Complete) - http://miktex.org/2.9/setup. Be sure to download the Complete installation. Click OK to open MiKTeX download page in the default browser. You may need to restart Visual Studio when the MiKTeX setup completes.
        ///.
        /// </summary>
        public static string Error_PdfLatexMissing {
            get {
                return ResourceManager.GetString("Error_PdfLatexMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete variable(s). Exception {0}.
        /// </summary>
        public static string Error_UnableToDeleteVariable {
            get {
                return ResourceManager.GetString("Error_UnableToDeleteVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to download Microsoft R Client. Exception {0}..
        /// </summary>
        public static string Error_UnableToDownloadRClient {
            get {
                return ResourceManager.GetString("Error_UnableToDownloadRClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout downloading Microsoft R Client installer executable..
        /// </summary>
        public static string Error_UnableToDownloadRClient_Timeout {
            get {
                return ResourceManager.GetString("Error_UnableToDownloadRClient_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a known CRAN mirror name..
        /// </summary>
        public static string Error_UnknownMirror {
            get {
                return ResourceManager.GetString("Error_UnknownMirror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gathering diagnostics data....
        /// </summary>
        public static string GatheringDiagnosticData {
            get {
                return ResourceManager.GetString("GatheringDiagnosticData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        public static string HelpBrowser_Automatic {
            get {
                return ResourceManager.GetString("HelpBrowser_Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External.
        /// </summary>
        public static string HelpBrowser_External {
            get {
                return ResourceManager.GetString("HelpBrowser_External", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type text to search for in R Help.
        /// </summary>
        public static string HelpSearchTooltip {
            get {
                return ResourceManager.GetString("HelpSearchTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type search term.
        /// </summary>
        public static string HelpSearchWatermark {
            get {
                return ResourceManager.GetString("HelpSearchWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Help.
        /// </summary>
        public static string HelpWindowCaption {
            get {
                return ResourceManager.GetString("HelpWindowCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R History Files (*.rhistory)|*.rhistory|All Files (*.*)|*.*.
        /// </summary>
        public static string HistoryFileFilter {
            get {
                return ResourceManager.GetString("HistoryFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R History.
        /// </summary>
        public static string HistoryWindowCaption {
            get {
                return ResourceManager.GetString("HistoryWindowCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comma (,).
        /// </summary>
        public static string ImportData_Comma {
            get {
                return ResourceManager.GetString("ImportData_Comma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double quote (&quot;).
        /// </summary>
        public static string ImportData_DoubleQuote {
            get {
                return ResourceManager.GetString("ImportData_DoubleQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Dataset Into R Session From Text File.
        /// </summary>
        public static string ImportData_EnterTextFileTitle {
            get {
                return ResourceManager.GetString("ImportData_EnterTextFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Dataset Into R Session From Web URL.
        /// </summary>
        public static string ImportData_EnterUrlTitle {
            get {
                return ResourceManager.GetString("ImportData_EnterUrlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string ImportData_None {
            get {
                return ResourceManager.GetString("ImportData_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NRows value must be integer that is greater than zero..
        /// </summary>
        public static string ImportData_NRowsError {
            get {
                return ResourceManager.GetString("ImportData_NRowsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period (.).
        /// </summary>
        public static string ImportData_Period {
            get {
                return ResourceManager.GetString("ImportData_Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semicolon (;).
        /// </summary>
        public static string ImportData_Semicolon {
            get {
                return ResourceManager.GetString("ImportData_Semicolon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single quote (&apos;).
        /// </summary>
        public static string ImportData_SingleQuote {
            get {
                return ResourceManager.GetString("ImportData_SingleQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab (\t).
        /// </summary>
        public static string ImportData_Tab {
            get {
                return ResourceManager.GetString("ImportData_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Dataset.
        /// </summary>
        public static string ImportData_Title {
            get {
                return ResourceManager.GetString("ImportData_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use first column.
        /// </summary>
        public static string ImportData_UseFirstColumn {
            get {
                return ResourceManager.GetString("ImportData_UseFirstColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use number.
        /// </summary>
        public static string ImportData_UseNumber {
            get {
                return ResourceManager.GetString("ImportData_UseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White space.
        /// </summary>
        public static string ImportData_Whitespace {
            get {
                return ResourceManager.GetString("ImportData_Whitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing....
        /// </summary>
        public static string Importing {
            get {
                return ResourceManager.GetString("Importing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input is too long - no more than {0} characters expected..
        /// </summary>
        public static string InputIsTooLong {
            get {
                return ResourceManager.GetString("InputIsTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Snippet....
        /// </summary>
        public static string InsertSnippet {
            get {
                return ResourceManager.GetString("InsertSnippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.
        /// </summary>
        public static string LanguageName {
            get {
                return ResourceManager.GetString("LanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No startup file specified for the startup project. Startup file can be specified in project properties..
        /// </summary>
        public static string Launch_NoStartupFile {
            get {
                return ResourceManager.GetString("Launch_NoStartupFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load History.
        /// </summary>
        public static string LoadHistoryTitle {
            get {
                return ResourceManager.GetString("LoadHistoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load workspace from {0} failed:
        ///{1}.
        /// </summary>
        public static string LoadWorkspaceFailedMessageFormat {
            get {
                return ResourceManager.GetString("LoadWorkspaceFailedMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to load the R data file {0} into the global environment?.
        /// </summary>
        public static string LoadWorkspaceIntoGlobalEnvironment {
            get {
                return ResourceManager.GetString("LoadWorkspaceIntoGlobalEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Workspace.
        /// </summary>
        public static string LoadWorkspaceTitle {
            get {
                return ResourceManager.GetString("LoadWorkspaceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Item {0} of {1}.
        /// </summary>
        public static string LongOperationProgressMessage1 {
            get {
                return ResourceManager.GetString("LongOperationProgressMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Item {0} of {1}: {2}.
        /// </summary>
        public static string LongOperationProgressMessage2 {
            get {
                return ResourceManager.GetString("LongOperationProgressMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Markdown.
        /// </summary>
        public static string MarkdownWindowTitle {
            get {
                return ResourceManager.GetString("MarkdownWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft R Client is already installed..
        /// </summary>
        public static string Message_RClientIsAlreadyInstalled {
            get {
                return ResourceManager.GetString("Message_RClientIsAlreadyInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current R engine is already set to the Microsoft R Client..
        /// </summary>
        public static string Message_RClientIsAlreadySet {
            get {
                return ResourceManager.GetString("Message_RClientIsAlreadySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting R Session....
        /// </summary>
        public static string MicrosoftRHostStarting {
            get {
                return ResourceManager.GetString("MicrosoftRHostStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Host process is stopped. Click Reset to start a new one..
        /// </summary>
        public static string MicrosoftRHostStopped {
            get {
                return ResourceManager.GetString("MicrosoftRHostStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping R Session....
        /// </summary>
        public static string MicrosoftRHostStopping {
            get {
                return ResourceManager.GetString("MicrosoftRHostStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Tools News.
        /// </summary>
        public static string NewsWindowTitle {
            get {
                return ResourceManager.GetString("NewsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in Microsoft Excel or another app registered for CSV files.
        /// </summary>
        public static string OpenCsvAppCommandTooltip {
            get {
                return ResourceManager.GetString("OpenCsvAppCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help on {0}.
        /// </summary>
        public static string OpenFunctionHelp {
            get {
                return ResourceManager.GetString("OpenFunctionHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to open RStudio project file as Visual Studio R project please select File | Open Project, locate .rproj file and click Open..
        /// </summary>
        public static string OpenRProjMessage {
            get {
                return ResourceManager.GetString("OpenRProjMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS Default.
        /// </summary>
        public static string OSDefaultEncoding {
            get {
                return ResourceManager.GetString("OSDefaultEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Packages.
        /// </summary>
        public static string OutputWindowName_InstallPackages {
            get {
                return ResourceManager.GetString("OutputWindowName_InstallPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Publish.
        /// </summary>
        public static string OutputWindowName_Publish {
            get {
                return ResourceManager.GetString("OutputWindowName_Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Package Manager.
        /// </summary>
        public static string PackageManagerWindowCaption {
            get {
                return ResourceManager.GetString("PackageManagerWindowCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft R Client setup is about to start. Please close Visual Studio now and reopen it when setup is complete..
        /// </summary>
        public static string PleaseRestartVisualStudioAfterRClientSetup {
            get {
                return ResourceManager.GetString("PleaseRestartVisualStudioAfterRClientSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Plot History.
        /// </summary>
        public static string PlotHistoryWindowCaption {
            get {
                return ResourceManager.GetString("PlotHistoryWindowCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Plot.
        /// </summary>
        public static string PlotWindowCaption {
            get {
                return ResourceManager.GetString("PlotWindowCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Studio detected that Microsoft R Client was recently installed. Would you like to start using R from the Microsoft R Client?.
        /// </summary>
        public static string Prompt_MsRClientJustInstalled {
            get {
                return ResourceManager.GetString("Prompt_MsRClientJustInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft R Client is not installed. Click Yes if you would you like to start installation of the Microsoft R Client now. Please close Visual Studio when the setup application starts and reopen it when Microsoft R Client installation is complete..
        /// </summary>
        public static string Prompt_RClientNotInstalled {
            get {
                return ResourceManager.GetString("Prompt_RClientNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;different options&gt;.
        /// </summary>
        public static string PropertyPageDifferentOptions {
            get {
                return ResourceManager.GetString("PropertyPageDifferentOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RDataNode {
            get {
                object obj = ResourceManager.GetObject("RDataNode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ReplWindowIcon {
            get {
                object obj = ResourceManager.GetObject("ReplWindowIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Interactive.
        /// </summary>
        public static string ReplWindowName {
            get {
                return ResourceManager.GetString("ReplWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please briefly describe what you were doing that led to the issue, if applicable:
        ///
        ///...
        ///
        ///If you have any screenshots demonstrating the issue, please include them as well to help us diagnose it better.
        ///
        ///
        ///
        ///Additional information:
        ///
        ///{0}.
        /// </summary>
        public static string ReportIssueBody {
            get {
                return ResourceManager.GetString("ReportIssueBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RFileNode {
            get {
                object obj = ResourceManager.GetObject("RFileNode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must restart Visual Studio after changing path to the R installation..
        /// </summary>
        public static string RPathChangedRestartVS {
            get {
                return ResourceManager.GetString("RPathChangedRestartVS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RProjectNode {
            get {
                object obj = ResourceManager.GetObject("RProjectNode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Interactive Prompts.
        /// </summary>
        public static string RPromptClassification {
            get {
                return ResourceManager.GetString("RPromptClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string RunPropertyPageTitle {
            get {
                return ResourceManager.GetString("RunPropertyPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown Files (*.md;*.rmd;*.markdown)|*.md;*.rmd;*.markdown|.
        /// </summary>
        public static string SaveAsFilterMD {
            get {
                return ResourceManager.GetString("SaveAsFilterMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Language Files (*.r)|*.r|.
        /// </summary>
        public static string SaveAsFilterR {
            get {
                return ResourceManager.GetString("SaveAsFilterR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save History As.
        /// </summary>
        public static string SaveHistoryAsTitle {
            get {
                return ResourceManager.GetString("SaveHistoryAsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Workspace As.
        /// </summary>
        public static string SaveWorkspaceAsTitle {
            get {
                return ResourceManager.GetString("SaveWorkspaceAsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save workspace into {0} failed:
        ///{1}.
        /// </summary>
        public static string SaveWorkspaceFailedMessageFormat {
            get {
                return ResourceManager.GetString("SaveWorkspaceFailedMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save current workspace image to {0}?.
        /// </summary>
        public static string SaveWorkspaceOnProjectUnload {
            get {
                return ResourceManager.GetString("SaveWorkspaceOnProjectUnload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Web for {0}.
        /// </summary>
        public static string SearchWebFor {
            get {
                return ResourceManager.GetString("SearchWebFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please briefly describe what you were doing that led to the issue, if applicable:
        ///
        ///...
        ///
        ///If you have any screenshots demonstrating the issue, please include them as well to help us diagnose it better.
        ///
        ///A detailed diagnostic log has been created at {0}, and a Windows Explorer window has been opened for that location with the log file selected. To improve our ability to diagnose the issue, you can attach that file to the email. However, be aware that the log may contain sensitive information, including i [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SendFrownEmailBody {
            get {
                return ResourceManager.GetString("SendFrownEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will now try to open your email client with a pre-created feedback email. If the email client does not open, please send an email message to rtvsuserfeedback@microsoft.com with the following information:.
        /// </summary>
        public static string SendMailFallbackMessage {
            get {
                return ResourceManager.GetString("SendMailFallbackMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always save history.
        /// </summary>
        public static string Settings_AlwaysSaveHistory {
            get {
                return ResourceManager.GetString("Settings_AlwaysSaveHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save history to .RHistory file when project is closed, even if workspace isn&apos;t saved.
        /// </summary>
        public static string Settings_AlwaysSaveHistory_Description {
            get {
                return ResourceManager.GetString("Settings_AlwaysSaveHistory_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic formatting.
        /// </summary>
        public static string Settings_AutoFormat {
            get {
                return ResourceManager.GetString("Settings_AutoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reformat code as you type.
        /// </summary>
        public static string Settings_AutoFormat_Description {
            get {
                return ResourceManager.GetString("Settings_AutoFormat_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expanded braces.
        /// </summary>
        public static string Settings_BracesExpanded {
            get {
                return ResourceManager.GetString("Settings_BracesExpanded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place open curly brace on a new line.
        /// </summary>
        public static string Settings_BracesExpanded_Description {
            get {
                return ResourceManager.GetString("Settings_BracesExpanded_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset search filter.
        /// </summary>
        public static string Settings_ClearFilterOnAddHistory {
            get {
                return ResourceManager.GetString("Settings_ClearFilterOnAddHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset search filter in history window when new entry is added or .RHistory file is loaded.
        /// </summary>
        public static string Settings_ClearFilterOnAddHistory_Description {
            get {
                return ResourceManager.GetString("Settings_ClearFilterOnAddHistory_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit on Enter key.
        /// </summary>
        public static string Settings_CommitOnEnter {
            get {
                return ResourceManager.GetString("Settings_CommitOnEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit intellisense selection when Enter key is pressed.
        /// </summary>
        public static string Settings_CommitOnEnter_Description {
            get {
                return ResourceManager.GetString("Settings_CommitOnEnter_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit on Space key.
        /// </summary>
        public static string Settings_CommitOnSpace {
            get {
                return ResourceManager.GetString("Settings_CommitOnSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit intellisense selection when Space key is pressed.
        /// </summary>
        public static string Settings_CommitOnSpace_Description {
            get {
                return ResourceManager.GetString("Settings_CommitOnSpace_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completion.
        /// </summary>
        public static string Settings_CompletionCategory {
            get {
                return ResourceManager.GetString("Settings_CompletionCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRAN Mirror.
        /// </summary>
        public static string Settings_CranMirror {
            get {
                return ResourceManager.GetString("Settings_CranMirror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default CRAN mirror for package installations.
        /// </summary>
        public static string Settings_CranMirror_Description {
            get {
                return ResourceManager.GetString("Settings_CranMirror_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debugging.
        /// </summary>
        public static string Settings_DebuggingCategory {
            get {
                return ResourceManager.GetString("Settings_DebuggingCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (OS Default).
        /// </summary>
        public static string Settings_DefaultValue {
            get {
                return ResourceManager.GetString("Settings_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show syntax errors.
        /// </summary>
        public static string Settings_EnableSyntaxCheck {
            get {
                return ResourceManager.GetString("Settings_EnableSyntaxCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable automatic syntax checking in the code.
        /// </summary>
        public static string Settings_EnableSyntaxCheck_Description {
            get {
                return ResourceManager.GetString("Settings_EnableSyntaxCheck_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluate active bindings.
        /// </summary>
        public static string Settings_EvaluateActiveBindings {
            get {
                return ResourceManager.GetString("Settings_EvaluateActiveBindings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically evaluate active bindings and display the resulting value. Warning: when this option is on, inspecting active bindings in Variable Explorer and debugger tool windows may change program state.
        /// </summary>
        public static string Settings_EvaluateActiveBindings_Description {
            get {
                return ResourceManager.GetString("Settings_EvaluateActiveBindings_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format on paste.
        /// </summary>
        public static string Settings_FormatOnPaste {
            get {
                return ResourceManager.GetString("Settings_FormatOnPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically format and indent code fragment on paste.
        /// </summary>
        public static string Settings_FormatOnPaste_Description {
            get {
                return ResourceManager.GetString("Settings_FormatOnPaste_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format scope on }.
        /// </summary>
        public static string Settings_FormatScope {
            get {
                return ResourceManager.GetString("Settings_FormatScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format scope after closing curly brace was typed.
        /// </summary>
        public static string Settings_FormatScope_Description {
            get {
                return ResourceManager.GetString("Settings_FormatScope_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatting.
        /// </summary>
        public static string Settings_FormattingCategory {
            get {
                return ResourceManager.GetString("Settings_FormattingCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Settings_GeneralCategory {
            get {
                return ResourceManager.GetString("Settings_GeneralCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Help Browser.
        /// </summary>
        public static string Settings_HelpBrowser {
            get {
                return ResourceManager.GetString("Settings_HelpBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines if R Tools should always be using external Web browser or try and send R Help pages to the R Help tool window. This setting does not affect F1 Web search..
        /// </summary>
        public static string Settings_HelpBrowser_Description {
            get {
                return ResourceManager.GetString("Settings_HelpBrowser_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Settings_HelpCategory {
            get {
                return ResourceManager.GetString("Settings_HelpCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string Settings_HistoryCategory {
            get {
                return ResourceManager.GetString("Settings_HistoryCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IntelliSense.
        /// </summary>
        public static string Settings_IntellisenseCategory {
            get {
                return ResourceManager.GetString("Settings_IntellisenseCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load workspace when project opens.
        /// </summary>
        public static string Settings_LoadRDataOnProjectLoad {
            get {
                return ResourceManager.GetString("Settings_LoadRDataOnProjectLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load workspace from .RData into global environment when project is opened.
        /// </summary>
        public static string Settings_LoadRDataOnProjectLoad_Description {
            get {
                return ResourceManager.GetString("Settings_LoadRDataOnProjectLoad_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown preview browser.
        /// </summary>
        public static string Settings_MarkdownBrowserType {
            get {
                return ResourceManager.GetString("Settings_MarkdownBrowserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines if generated R Markdown pages should be opened in internal Visual Studio browser or in the external Web browser..
        /// </summary>
        public static string Settings_MarkdownBrowserType_Description {
            get {
                return ResourceManager.GetString("Settings_MarkdownBrowserType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown.
        /// </summary>
        public static string Settings_MarkdownCategory {
            get {
                return ResourceManager.GetString("Settings_MarkdownCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use multiline selection.
        /// </summary>
        public static string Settings_MultilineHistorySelection {
            get {
                return ResourceManager.GetString("Settings_MultilineHistorySelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single click in R history window selects the entire fragment that was sent to R. Up/Down arrows in the R Interactive Window navigate through chunks instead of single lines..
        /// </summary>
        public static string Settings_MultilineHistorySelection_Description {
            get {
                return ResourceManager.GetString("Settings_MultilineHistorySelection_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (OS Default).
        /// </summary>
        public static string Settings_OsDefaultEncoding {
            get {
                return ResourceManager.GetString("Settings_OsDefaultEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match partially typed argument names.
        /// </summary>
        public static string Settings_PartialArgumentNameMatch {
            get {
                return ResourceManager.GetString("Settings_PartialArgumentNameMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When typing argument name in a function call, signature help shows description for the argument that is the best match.
        /// </summary>
        public static string Settings_PartialArgumentNameMatch_Description {
            get {
                return ResourceManager.GetString("Settings_PartialArgumentNameMatch_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Engine (64-bit).
        /// </summary>
        public static string Settings_RBasePath {
            get {
                return ResourceManager.GetString("Settings_RBasePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to R installation (64-bit only)..
        /// </summary>
        public static string Settings_RBasePath_Description {
            get {
                return ResourceManager.GetString("Settings_RBasePath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code page.
        /// </summary>
        public static string Settings_RCodePage {
            get {
                return ResourceManager.GetString("Settings_RCodePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default code page in R. Affects conversion of characters from Windows Unicode to R and back. Same as in Sys.setlocale(LC_CTYPE)..
        /// </summary>
        public static string Settings_RCodePage_Description {
            get {
                return ResourceManager.GetString("Settings_RCodePage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R command line arguments.
        /// </summary>
        public static string Settings_RCommandLineArguments {
            get {
                return ResourceManager.GetString("Settings_RCommandLineArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional arguments to pass to the R Host process.
        /// </summary>
        public static string Settings_RCommandLineArguments_Description {
            get {
                return ResourceManager.GetString("Settings_RCommandLineArguments_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Engine.
        /// </summary>
        public static string Settings_REngineCategory {
            get {
                return ResourceManager.GetString("Settings_REngineCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interactive window.
        /// </summary>
        public static string Settings_ReplCategory {
            get {
                return ResourceManager.GetString("Settings_ReplCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax check in R Console.
        /// </summary>
        public static string Settings_ReplSyntaxCheck {
            get {
                return ResourceManager.GetString("Settings_ReplSyntaxCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turns on or off live code syntax check in R Console window. Syntax check may not work correctly in multi-line statements..
        /// </summary>
        public static string Settings_ReplSyntaxCheck_Description {
            get {
                return ResourceManager.GetString("Settings_ReplSyntaxCheck_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save workspace when project closes.
        /// </summary>
        public static string Settings_SaveRDataOnProjectUnload {
            get {
                return ResourceManager.GetString("Settings_SaveRDataOnProjectUnload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save workspace from global environment to .RData when project is closed.
        /// </summary>
        public static string Settings_SaveRDataOnProjectUnload_Description {
            get {
                return ResourceManager.GetString("Settings_SaveRDataOnProjectUnload_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shiny pages browser.
        /// </summary>
        public static string Settings_ShinyBrowserType {
            get {
                return ResourceManager.GetString("Settings_ShinyBrowserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines if Shiny pages should be opened in internal Visual Studio browser or in the external Web browser..
        /// </summary>
        public static string Settings_ShinyBrowserType_Description {
            get {
                return ResourceManager.GetString("Settings_ShinyBrowserType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shiny.
        /// </summary>
        public static string Settings_ShinyCategory {
            get {
                return ResourceManager.GetString("Settings_ShinyCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show dot-prefixed variables.
        /// </summary>
        public static string Settings_ShowDotPrefixedVariables {
            get {
                return ResourceManager.GetString("Settings_ShowDotPrefixedVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show variables that have names beginning with &quot;.&quot; in Variable Explorer and debugger tool windows..
        /// </summary>
        public static string Settings_ShowDotPrefixedVariables_Description {
            get {
                return ResourceManager.GetString("Settings_ShowDotPrefixedVariables_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show internal functions.
        /// </summary>
        public static string Settings_ShowInternalFunctions {
            get {
                return ResourceManager.GetString("Settings_ShowInternalFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show internal functions (functions beginning with dot) in the statement completion list.
        /// </summary>
        public static string Settings_ShowInternalFunctions_Description {
            get {
                return ResourceManager.GetString("Settings_ShowInternalFunctions_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show TCL functions.
        /// </summary>
        public static string Settings_ShowTclFunctions {
            get {
                return ResourceManager.GetString("Settings_ShowTclFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show functions from TCL/TK package in the statement completion list.
        /// </summary>
        public static string Settings_ShowTclFunctions_Description {
            get {
                return ResourceManager.GetString("Settings_ShowTclFunctions_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space after comma.
        /// </summary>
        public static string Settings_SpaceAfterComma {
            get {
                return ResourceManager.GetString("Settings_SpaceAfterComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert space after comma in function arguments.
        /// </summary>
        public static string Settings_SpaceAfterComma_Description {
            get {
                return ResourceManager.GetString("Settings_SpaceAfterComma_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space after keyword.
        /// </summary>
        public static string Settings_SpaceAfterKeyword {
            get {
                return ResourceManager.GetString("Settings_SpaceAfterKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert space after keyword and before opening brace such as in case of &apos;if&apos;, &apos;while&apos;, &apos;repeat&apos;.
        /// </summary>
        public static string Settings_SpaceAfterKeyword_Description {
            get {
                return ResourceManager.GetString("Settings_SpaceAfterKeyword_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey/News Check.
        /// </summary>
        public static string Settings_SurveyNewsCheck {
            get {
                return ResourceManager.GetString("Settings_SurveyNewsCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies how often R Tools should check with the server for news and survey updates..
        /// </summary>
        public static string Settings_SurveyNewsCheck_Description {
            get {
                return ResourceManager.GetString("Settings_SurveyNewsCheck_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax check.
        /// </summary>
        public static string Settings_SyntaxCheckCategory {
            get {
                return ResourceManager.GetString("Settings_SyntaxCheckCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completion list on first character.
        /// </summary>
        public static string Settings_TriggerOnFirstChar {
            get {
                return ResourceManager.GetString("Settings_TriggerOnFirstChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show completion list on first character typed. If set to off, completion list can be brought up by invoking Edit &gt; IntelliSense &gt; List Members command (typically Ctrl+J).
        /// </summary>
        public static string Settings_TriggerOnFirstChar_Description {
            get {
                return ResourceManager.GetString("Settings_TriggerOnFirstChar_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completion list on Tab key.
        /// </summary>
        public static string Settings_TriggerOnTab {
            get {
                return ResourceManager.GetString("Settings_TriggerOnTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If set to on completion list can be invoked by typing one or more characters and pressing Tab..
        /// </summary>
        public static string Settings_TriggerOnTab_Description {
            get {
                return ResourceManager.GetString("Settings_TriggerOnTab_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F1 Web browser.
        /// </summary>
        public static string Settings_WebHelpSearchBrowserType {
            get {
                return ResourceManager.GetString("Settings_WebHelpSearchBrowserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines if F1 Web search should be using internal Visual Studio Web browser or an external Web browser..
        /// </summary>
        public static string Settings_WebHelpSearchBrowserType_Description {
            get {
                return ResourceManager.GetString("Settings_WebHelpSearchBrowserType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F1 Web search string.
        /// </summary>
        public static string Settings_WebHelpSearchString {
            get {
                return ResourceManager.GetString("Settings_WebHelpSearchString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String to append to the F1 Web search query after the search item..
        /// </summary>
        public static string Settings_WebHelpSearchString_Description {
            get {
                return ResourceManager.GetString("Settings_WebHelpSearchString_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspace.
        /// </summary>
        public static string Settings_WorkspaceCategory {
            get {
                return ResourceManager.GetString("Settings_WorkspaceCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Shiny.
        /// </summary>
        public static string ShinyWindowTitle {
            get {
                return ResourceManager.GetString("ShinyWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show item details.
        /// </summary>
        public static string ShowDetailCommandTooltip {
            get {
                return ResourceManager.GetString("ShowDetailCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing data into CSV file....
        /// </summary>
        public static string Status_WritingCSV {
            get {
                return ResourceManager.GetString("Status_WritingCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surround With.
        /// </summary>
        public static string SurrondWithSnippet {
            get {
                return ResourceManager.GetString("SurrondWithSnippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once a day.
        /// </summary>
        public static string SurveyNewsPolicyCheckOnceDay {
            get {
                return ResourceManager.GetString("SurveyNewsPolicyCheckOnceDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once a month.
        /// </summary>
        public static string SurveyNewsPolicyCheckOnceMonth {
            get {
                return ResourceManager.GetString("SurveyNewsPolicyCheckOnceMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once a week.
        /// </summary>
        public static string SurveyNewsPolicyCheckOnceWeek {
            get {
                return ResourceManager.GetString("SurveyNewsPolicyCheckOnceWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        public static string SurveyNewsPolicyDisabled {
            get {
                return ResourceManager.GetString("SurveyNewsPolicyDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching data....
        /// </summary>
        public static string TooltipPlaceholder {
            get {
                return ResourceManager.GetString("TooltipPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format Document.
        /// </summary>
        public static string UndoActionFormatDocument {
            get {
                return ResourceManager.GetString("UndoActionFormatDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string VariableExplorer_ClassHeader {
            get {
                return ResourceManager.GetString("VariableExplorer_ClassHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No R Interactive.
        /// </summary>
        public static string VariableExplorer_EnvironmentName {
            get {
                return ResourceManager.GetString("VariableExplorer_EnvironmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving environment list.
        /// </summary>
        public static string VariableExplorer_ErrorEnvironment {
            get {
                return ResourceManager.GetString("VariableExplorer_ErrorEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string VariableExplorer_NameHeader {
            get {
                return ResourceManager.GetString("VariableExplorer_NameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [truncated].
        /// </summary>
        public static string VariableExplorer_Truncated {
            get {
                return ResourceManager.GetString("VariableExplorer_Truncated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string VariableExplorer_TypeHeader {
            get {
                return ResourceManager.GetString("VariableExplorer_TypeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string VariableExplorer_ValueHeader {
            get {
                return ResourceManager.GetString("VariableExplorer_ValueHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Data.
        /// </summary>
        public static string VariableGrid_Caption {
            get {
                return ResourceManager.GetString("VariableGrid_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to object {0} is missing..
        /// </summary>
        public static string VariableGrid_Missing {
            get {
                return ResourceManager.GetString("VariableGrid_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to object {0} is not two dimensional..
        /// </summary>
        public static string VariableGrid_NotTwoDimension {
            get {
                return ResourceManager.GetString("VariableGrid_NotTwoDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable Explorer.
        /// </summary>
        public static string VariableWindowCaption {
            get {
                return ResourceManager.GetString("VariableWindowCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove all variables?.
        /// </summary>
        public static string Warning_DeleteAllVariables {
            get {
                return ResourceManager.GetString("Warning_DeleteAllVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to reset keyboard shortcuts to be compatible with the RStudio where possible?.
        /// </summary>
        public static string Warning_RStudioKeyboardShortcuts {
            get {
                return ResourceManager.GetString("Warning_RStudioKeyboardShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current file cannot be saved in the current encoding. Do you want to save file in UTF-8 and continue?.
        /// </summary>
        public static string Warning_SaveInUtf8 {
            get {
                return ResourceManager.GetString("Warning_SaveInUtf8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will reset Visual Studio window layout to the Data Scientist profile. If you prefer to save existing Visual Studio settings please use Tools &gt; Import/Export Settings instead to switch profiles. You can also go back to the original VS settings profile via Import/Export Settings. Proceed?.
        /// </summary>
        public static string Warning_SettingsReset {
            get {
                return ResourceManager.GetString("Warning_SettingsReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project appears to be on a network share. R Tools for Visual Studio may not work correctly when files are on a remote share. .
        /// </summary>
        public static string Warning_UncPath {
            get {
                return ResourceManager.GetString("Warning_UncPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Web Help.
        /// </summary>
        public static string WebHelpWindowTitle {
            get {
                return ResourceManager.GetString("WebHelpWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Data Files (*.rdata)|*.rdata|All Files (*.*)|*.*.
        /// </summary>
        public static string WorkspaceFileFilter {
            get {
                return ResourceManager.GetString("WorkspaceFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
