//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.R.Components {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.R.Components.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to the workspace has been terminated..
        /// </summary>
        public static string BrokerDisconnected {
            get {
                return ResourceManager.GetString("BrokerDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error.
        /// </summary>
        public static string ConfigurationError_Syntax {
            get {
                return ResourceManager.GetString("ConfigurationError_Syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected users: {0}.
        /// </summary>
        public static string ConnectedUserCount {
            get {
                return ResourceManager.GetString("ConnectedUserCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string ConnectionManager_Add {
            get {
                return ResourceManager.GetString("ConnectionManager_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ConnectionManager_Cancel {
            get {
                return ResourceManager.GetString("ConnectionManager_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t change connection name to &apos;{0}&apos; because connection with the same name already exists..
        /// </summary>
        public static string ConnectionManager_CantSaveWithTheSameName {
            get {
                return ResourceManager.GetString("ConnectionManager_CantSaveWithTheSameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string ConnectionManager_Connect {
            get {
                return ResourceManager.GetString("ConnectionManager_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string ConnectionManager_Connected {
            get {
                return ResourceManager.GetString("ConnectionManager_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection &quot;{0}&quot; has the same parameters as &quot;{1}&quot; and is already connected..
        /// </summary>
        public static string ConnectionManager_ConnectionsAreIdentical {
            get {
                return ResourceManager.GetString("ConnectionManager_ConnectionsAreIdentical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to &quot;{0}&quot;.
        /// </summary>
        public static string ConnectionManager_ConnectionToProgressBarMessage {
            get {
                return ResourceManager.GetString("ConnectionManager_ConnectionToProgressBarMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to &apos;{0}&apos;.
        /// </summary>
        public static string ConnectionManager_ConnectTooltip {
            get {
                return ResourceManager.GetString("ConnectionManager_ConnectTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting &quot;{0}&quot;.
        /// </summary>
        public static string ConnectionManager_DeleteConnectionProgressBarMessage {
            get {
                return ResourceManager.GetString("ConnectionManager_DeleteConnectionProgressBarMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete connection &apos;{0}&apos;.
        /// </summary>
        public static string ConnectionManager_DeleteTooltip_Format {
            get {
                return ResourceManager.GetString("ConnectionManager_DeleteTooltip_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry for the automatically detected local R cannot be deleted. It will be removed when this R version is uninstalled..
        /// </summary>
        public static string ConnectionManager_DeleteTooltipDisabled {
            get {
                return ResourceManager.GetString("ConnectionManager_DeleteTooltipDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        public static string ConnectionManager_Disconnected {
            get {
                return ResourceManager.GetString("ConnectionManager_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edited connection has unsaved changes. Do you want to save them?.
        /// </summary>
        public static string ConnectionManager_EditedConnectionHasChanges {
            get {
                return ResourceManager.GetString("ConnectionManager_EditedConnectionHasChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit local connection &apos;{0}&apos;.
        /// </summary>
        public static string ConnectionManager_EditLocalTooltip_Format {
            get {
                return ResourceManager.GetString("ConnectionManager_EditLocalTooltip_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit remote connection &apos;{0}&apos;.
        /// </summary>
        public static string ConnectionManager_EditRemoteTooltip_Format {
            get {
                return ResourceManager.GetString("ConnectionManager_EditRemoteTooltip_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path: {0}
        ///Arguments: {1}.
        /// </summary>
        public static string ConnectionManager_InformationTooltipFormatLocal {
            get {
                return ResourceManager.GetString("ConnectionManager_InformationTooltipFormatLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host: {0}
        ///Arguments: {1}.
        /// </summary>
        public static string ConnectionManager_InformationTooltipFormatRemote {
            get {
                return ResourceManager.GetString("ConnectionManager_InformationTooltipFormatRemote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided name is invalid. Allowed characters are letters, digits, underscore, period, dash, single quote, braces and square brackets..
        /// </summary>
        public static string ConnectionManager_InvalidName {
            get {
                return ResourceManager.GetString("ConnectionManager_InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL or path is not a valid. Please specify full path to the local R or remote machine connection URL in the form &apos;[https://]machine[:port]&apos;.
        /// </summary>
        public static string ConnectionManager_InvalidPath {
            get {
                return ResourceManager.GetString("ConnectionManager_InvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        public static string ConnectionManager_LocalConnections {
            get {
                return ResourceManager.GetString("ConnectionManager_LocalConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local R installations.
        /// </summary>
        public static string ConnectionManager_LocalConnections_Tooltip {
            get {
                return ResourceManager.GetString("ConnectionManager_LocalConnections_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry name.
        /// </summary>
        public static string ConnectionManager_Name {
            get {
                return ResourceManager.GetString("ConnectionManager_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none specified.
        /// </summary>
        public static string ConnectionManager_None {
            get {
                return ResourceManager.GetString("ConnectionManager_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host URL or path to R installation.
        /// </summary>
        public static string ConnectionManager_Path {
            get {
                return ResourceManager.GetString("ConnectionManager_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R command line arguments.
        /// </summary>
        public static string ConnectionManager_RCommandLineArguments {
            get {
                return ResourceManager.GetString("ConnectionManager_RCommandLineArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnecting to &quot;{0}&quot;.
        /// </summary>
        public static string ConnectionManager_ReconnectionToProgressBarMessage {
            get {
                return ResourceManager.GetString("ConnectionManager_ReconnectionToProgressBarMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote.
        /// </summary>
        public static string ConnectionManager_RemoteConnections {
            get {
                return ResourceManager.GetString("ConnectionManager_RemoteConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote R installations.
        /// </summary>
        public static string ConnectionManager_RemoteConnections_Tooltip {
            get {
                return ResourceManager.GetString("ConnectionManager_RemoteConnections_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the &apos;{0}&apos; connection? 
        ///    
        ///Deleting it will terminate the active session and all unsaved data will be lost.
        ///
        ///Removing the connection will not delete files you may have created on the remote machine.
        ///If you want to delete all data on the remote machine you must delete your user profile first..
        /// </summary>
        public static string ConnectionManager_RemoveActiveConnectionConfirmation {
            get {
                return ResourceManager.GetString("ConnectionManager_RemoveActiveConnectionConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the &apos;{0}&apos; connection?.
        /// </summary>
        public static string ConnectionManager_RemoveConnectionConfirmation {
            get {
                return ResourceManager.GetString("ConnectionManager_RemoveConnectionConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving changes will terminate the active session and all unsaved data will be lost.
        ///
        ///Do you wish to proceed?.
        /// </summary>
        public static string ConnectionManager_RenameActiveConnectionConfirmation {
            get {
                return ResourceManager.GetString("ConnectionManager_RenameActiveConnectionConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renaming &quot;{0}&quot; to &quot;{1}&quot;.
        /// </summary>
        public static string ConnectionManager_RenameConnectionProgressBarMessage {
            get {
                return ResourceManager.GetString("ConnectionManager_RenameConnectionProgressBarMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ConnectionManager_Save {
            get {
                return ResourceManager.GetString("ConnectionManager_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection should have name specified..
        /// </summary>
        public static string ConnectionManager_ShouldHaveName {
            get {
                return ResourceManager.GetString("ConnectionManager_ShouldHaveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection should have path specified..
        /// </summary>
        public static string ConnectionManager_ShouldHavePath {
            get {
                return ResourceManager.GetString("ConnectionManager_ShouldHavePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to switch from &apos;{0}&apos; to &apos;{1}&apos;? Switching will stop your current session, all unsaved data will be lost.
        ///
        ///This prompt can be suppressed in R Tools | Options..
        /// </summary>
        public static string ConnectionManager_SwitchConfirmation {
            get {
                return ResourceManager.GetString("ConnectionManager_SwitchConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switching connection &quot;{0}&quot; to &quot;{1}&quot;.
        /// </summary>
        public static string ConnectionManager_SwitchConnectionProgressBarMessage {
            get {
                return ResourceManager.GetString("ConnectionManager_SwitchConnectionProgressBarMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Connection.
        /// </summary>
        public static string ConnectionManager_TestConnection {
            get {
                return ResourceManager.GetString("ConnectionManager_TestConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection test canceled..
        /// </summary>
        public static string ConnectionManager_TestConnectionCanceled {
            get {
                return ResourceManager.GetString("ConnectionManager_TestConnectionCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection test failed:
        ///{0}.
        /// </summary>
        public static string ConnectionManager_TestConnectionFailed_Format {
            get {
                return ResourceManager.GetString("ConnectionManager_TestConnectionFailed_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection path is invalid..
        /// </summary>
        public static string ConnectionManager_TestConnectionFailed_PathIsInvalid {
            get {
                return ResourceManager.GetString("ConnectionManager_TestConnectionFailed_PathIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.R.Host.exe is missing..
        /// </summary>
        public static string ConnectionManager_TestConnectionFailed_RHostIsMissing {
            get {
                return ResourceManager.GetString("ConnectionManager_TestConnectionFailed_RHostIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection test passed!.
        /// </summary>
        public static string ConnectionManager_TestConnectionPassed {
            get {
                return ResourceManager.GetString("ConnectionManager_TestConnectionPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test connection to the R interpreter. Authentication credentials may be required..
        /// </summary>
        public static string ConnectionManager_TestConnectionTooltip {
            get {
                return ResourceManager.GetString("ConnectionManager_TestConnectionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing connection....
        /// </summary>
        public static string ConnectionManager_TestingConnection {
            get {
                return ResourceManager.GetString("ConnectionManager_TestingConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING
        ///
        ///You are about to delete all of your files on the remote server!
        ///
        ///Your user profile and ALL FILES under your user directory will be PERMANENTLY DELETED from {0}. Your connection will also be terminated.
        ///
        ///Your local files are not affected.
        ///
        ///Reconnecting to the same remote server will create a brand new profile.  
        ///
        ///Are you sure you want to delete your user profile and all the associated remote files?.
        /// </summary>
        public static string DeleteProfile_DeletionWarning {
            get {
                return ResourceManager.GetString("DeleteProfile_DeletionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete user profile, try again few minutes later.
        ///If it continues to fail, please check the logs for RUserProfileService on the remote machine {0}..
        /// </summary>
        public static string DeleteProfile_Error {
            get {
                return ResourceManager.GetString("DeleteProfile_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User directory and files under it were successfully deleted from remote machine {0}. 
        ///You can click &quot;Reset&quot; to re-create your user profile and start a new session..
        /// </summary>
        public static string DeleteProfile_Success {
            get {
                return ResourceManager.GetString("DeleteProfile_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismiss.
        /// </summary>
        public static string Dismiss {
            get {
                return ResourceManager.GetString("Dismiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismiss all.
        /// </summary>
        public static string DismissAll {
            get {
                return ResourceManager.GetString("DismissAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not show this again.
        /// </summary>
        public static string DoNotShowThisAgain {
            get {
                return ResourceManager.GetString("DoNotShowThisAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression does not evaluate to function..
        /// </summary>
        public static string Error_CannotEditExpression {
            get {
                return ResourceManager.GetString("Error_CannotEditExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection string appears to be in incorrect format. Would you like to re-create it?.
        /// </summary>
        public static string Error_ConnectionStringFormat {
            get {
                return ResourceManager.GetString("Error_ConnectionStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save state, resetting anyway..
        /// </summary>
        public static string Error_FailedToSaveState {
            get {
                return ResourceManager.GetString("Error_FailedToSaveState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout installing package {0}..
        /// </summary>
        public static string Error_InstallTimeout_Format {
            get {
                return ResourceManager.GetString("Error_InstallTimeout_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to SQL database in Azure requires SQL ODBC driver 13.1 or higher. Please install the latest Microsoft ODBC Driver from {0}..
        /// </summary>
        public static string Error_OdbcDriver {
            get {
                return ResourceManager.GetString("Error_OdbcDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error rendering plot.
        /// </summary>
        public static string Error_RenderingPlot {
            get {
                return ResourceManager.GetString("Error_RenderingPlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command line text cannot be converted to default OS code page. Please set locale for non-Unicode programs in Control Panel -&gt; Region -&gt; Administrative to the locale you wish to use..
        /// </summary>
        public static string Error_ReplUnicodeCoversion {
            get {
                return ResourceManager.GetString("Error_ReplUnicodeCoversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings file {0} does not exists..
        /// </summary>
        public static string Error_SettingFileNoLongerExists {
            get {
                return ResourceManager.GetString("Error_SettingFileNoLongerExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to transfer file {0}. Exception: {1}..
        /// </summary>
        public static string Error_UnableToTransferFile {
            get {
                return ResourceManager.GetString("Error_UnableToTransferFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine utilization: {0}% CPU, {1}% Memory, {2}% Network..
        /// </summary>
        public static string HostLoad_Tooltip {
            get {
                return ResourceManager.GetString("HostLoad_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input is too long - no more than {0} characters expected..
        /// </summary>
        public static string InputIsTooLong {
            get {
                return ResourceManager.GetString("InputIsTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed R versions:.
        /// </summary>
        public static string InstalledInterpreters {
            get {
                return ResourceManager.GetString("InstalledInterpreters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading details....
        /// </summary>
        public static string LoadingDetails {
            get {
                return ResourceManager.GetString("LoadingDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local R: {0}.
        /// </summary>
        public static string LocalR {
            get {
                return ResourceManager.GetString("LocalR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting R session....
        /// </summary>
        public static string MicrosoftRHostStarting {
            get {
                return ResourceManager.GetString("MicrosoftRHostStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R session is stopped. Click &quot;Reset&quot; to start a new one..
        /// </summary>
        public static string MicrosoftRHostStopped {
            get {
                return ResourceManager.GetString("MicrosoftRHostStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping R session....
        /// </summary>
        public static string MicrosoftRHostStopping {
            get {
                return ResourceManager.GetString("MicrosoftRHostStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Studio is unable to find local R installation. Would you like to install Microsoft R Client (recommended)?{0}Click Yes to install latest Microsoft R Client. {1}Click No if you are planning to set up connection to a remote machine..
        /// </summary>
        public static string NoLocalR {
            get {
                return ResourceManager.GetString("NoLocalR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating System: {0}.
        /// </summary>
        public static string OperatingSystem {
            get {
                return ResourceManager.GetString("OperatingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package: {0}, State: {1}, {2}, Description: {3}.
        /// </summary>
        public static string Package_AccessibleDescription {
            get {
                return ResourceManager.GetString("Package_AccessibleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed.
        /// </summary>
        public static string Package_AccessibleState_Installed {
            get {
                return ResourceManager.GetString("Package_AccessibleState_Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded.
        /// </summary>
        public static string Package_AccessibleState_Loaded {
            get {
                return ResourceManager.GetString("Package_AccessibleState_Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not installed.
        /// </summary>
        public static string Package_AccessibleState_NotInstalled {
            get {
                return ResourceManager.GetString("Package_AccessibleState_NotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not loaded.
        /// </summary>
        public static string Package_AccessibleState_NotLoaded {
            get {
                return ResourceManager.GetString("Package_AccessibleState_NotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors:.
        /// </summary>
        public static string Package_Authors {
            get {
                return ResourceManager.GetString("Package_Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built:.
        /// </summary>
        public static string Package_Built {
            get {
                return ResourceManager.GetString("Package_Built", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depends:.
        /// </summary>
        public static string Package_Depends {
            get {
                return ResourceManager.GetString("Package_Depends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string Package_Description {
            get {
                return ResourceManager.GetString("Package_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imports:.
        /// </summary>
        public static string Package_Imports {
            get {
                return ResourceManager.GetString("Package_Imports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed version:.
        /// </summary>
        public static string Package_InstalledVersion {
            get {
                return ResourceManager.GetString("Package_InstalledVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest version:.
        /// </summary>
        public static string Package_LatestVersion {
            get {
                return ResourceManager.GetString("Package_LatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library:.
        /// </summary>
        public static string Package_LibraryPath {
            get {
                return ResourceManager.GetString("Package_LibraryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License:.
        /// </summary>
        public static string Package_License {
            get {
                return ResourceManager.GetString("Package_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository:.
        /// </summary>
        public static string Package_Repository {
            get {
                return ResourceManager.GetString("Package_Repository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggests:.
        /// </summary>
        public static string Package_Suggests {
            get {
                return ResourceManager.GetString("Package_Suggests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        public static string Package_Title {
            get {
                return ResourceManager.GetString("Package_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urls:.
        /// </summary>
        public static string Package_Urls {
            get {
                return ResourceManager.GetString("Package_Urls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string PackageManager_Available {
            get {
                return ResourceManager.GetString("PackageManager_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Package {0} can&apos;t be installed because Interactive Window is disconnected from R session..
        /// </summary>
        public static string PackageManager_CantInstallPackageNoRSession {
            get {
                return ResourceManager.GetString("PackageManager_CantInstallPackageNoRSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Can&apos;t get list of available packages because your R session is not running right now. Use the Workspaces window (R Tools | Windows | Workspaces) to start a new R session..
        /// </summary>
        public static string PackageManager_CantLoadAvailablePackages_NoConnection {
            get {
                return ResourceManager.GetString("PackageManager_CantLoadAvailablePackages_NoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Can&apos;t get list of installed packages because your R session is not running right now. Use the Workspaces window (R Tools | Windows | Workspaces) to start a new R session..
        /// </summary>
        public static string PackageManager_CantLoadInstalledPackages_NoConnection {
            get {
                return ResourceManager.GetString("PackageManager_CantLoadInstalledPackages_NoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Can&apos;t get list of loaded packages because your R session is not running right now. Use the Workspaces window (R Tools | Windows | Workspaces) to start a new R session..
        /// </summary>
        public static string PackageManager_CantLoadLoadedPackages_NoConnection {
            get {
                return ResourceManager.GetString("PackageManager_CantLoadLoadedPackages_NoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Package {0} can&apos;t be loaded because Interactive Window is disconnected from R session..
        /// </summary>
        public static string PackageManager_CantLoadPackageNoRSession {
            get {
                return ResourceManager.GetString("PackageManager_CantLoadPackageNoRSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Package {0} can&apos;t be uninstalled because Interactive Window is disconnected from R session..
        /// </summary>
        public static string PackageManager_CantUninstallPackageNoRSession {
            get {
                return ResourceManager.GetString("PackageManager_CantUninstallPackageNoRSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Package {0} can&apos;t be unloaded because Interactive Window is disconnected from R session..
        /// </summary>
        public static string PackageManager_CantUnloadPackageNoRSession {
            get {
                return ResourceManager.GetString("PackageManager_CantUnloadPackageNoRSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Package {0} can&apos;t be updated because Interactive Window is disconnected from R session..
        /// </summary>
        public static string PackageManager_CantUpdatePackageNoRSession {
            get {
                return ResourceManager.GetString("PackageManager_CantUpdatePackageNoRSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        public static string PackageManager_EvalError {
            get {
                return ResourceManager.GetString("PackageManager_EvalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing results returned by R host process..
        /// </summary>
        public static string PackageManager_EvalParseError {
            get {
                return ResourceManager.GetString("PackageManager_EvalParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R host process is not available..
        /// </summary>
        public static string PackageManager_EvalSessionNotAvailable {
            get {
                return ResourceManager.GetString("PackageManager_EvalSessionNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install {0} version {1}..
        /// </summary>
        public static string PackageManager_InstallButtonToolTip {
            get {
                return ResourceManager.GetString("PackageManager_InstallButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed.
        /// </summary>
        public static string PackageManager_Installed {
            get {
                return ResourceManager.GetString("PackageManager_Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed version: {0}.
        /// </summary>
        public static string PackageManager_InstalledVersionToolTip {
            get {
                return ResourceManager.GetString("PackageManager_InstalledVersionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest version: {0}.
        /// </summary>
        public static string PackageManager_LatestVersionToolTip {
            get {
                return ResourceManager.GetString("PackageManager_LatestVersionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each package is licensed to you by its owner. Microsoft is not responsible for, nor does it grant any licenses to, third-party packages..
        /// </summary>
        public static string PackageManager_LegalDisclaimer {
            get {
                return ResourceManager.GetString("PackageManager_LegalDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load {0}..
        /// </summary>
        public static string PackageManager_LoadButtonToolTip {
            get {
                return ResourceManager.GetString("PackageManager_LoadButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded.
        /// </summary>
        public static string PackageManager_Loaded {
            get {
                return ResourceManager.GetString("PackageManager_Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Interactive Window is disconnected from R Session, so there is no information about loaded packages..
        /// </summary>
        public static string PackageManager_NoLoadedPackagesNoRSession {
            get {
                return ResourceManager.GetString("PackageManager_NoLoadedPackagesNoRSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not available in this source.
        /// </summary>
        public static string PackageManager_NotAvailableInSource {
            get {
                return ResourceManager.GetString("PackageManager_NotAvailableInSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest stable version is installed.
        /// </summary>
        public static string PackageManager_PackageInstalledToolTip {
            get {
                return ResourceManager.GetString("PackageManager_PackageInstalledToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Package {0} can&apos;t be uninstalled because one of its files is locked by other process..
        /// </summary>
        public static string PackageManager_PackageLocked {
            get {
                return ResourceManager.GetString("PackageManager_PackageLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Package {0} can&apos;t be uninstalled because it has been loaded into R. You need to reset R before package can be uninstalled..
        /// </summary>
        public static string PackageManager_PackageLockedByRSession {
            get {
                return ResourceManager.GetString("PackageManager_PackageLockedByRSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package sources:.
        /// </summary>
        public static string PackageManager_PackageSources {
            get {
                return ResourceManager.GetString("PackageManager_PackageSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to permanently uninstall &apos;{0}&apos; package from library &apos;{1}&apos;? This action cannot be undone..
        /// </summary>
        public static string PackageManager_PackageUninstallWarning {
            get {
                return ResourceManager.GetString("PackageManager_PackageUninstallWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to update &apos;{0}&apos; package? This action cannot be undone..
        /// </summary>
        public static string PackageManager_PackageUpdateWarning {
            get {
                return ResourceManager.GetString("PackageManager_PackageUpdateWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prerelease.
        /// </summary>
        public static string PackageManager_Prerelease {
            get {
                return ResourceManager.GetString("PackageManager_Prerelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving results from one or more sources.
        /// </summary>
        public static string PackageManager_SearchIncomplete {
            get {
                return ResourceManager.GetString("PackageManager_SearchIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all packages.
        /// </summary>
        public static string PackageManager_SelectAllPackages {
            get {
                return ResourceManager.GetString("PackageManager_SelectAllPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show errors in output.
        /// </summary>
        public static string PackageManager_ShowErrors {
            get {
                return ResourceManager.GetString("PackageManager_ShowErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Manager.
        /// </summary>
        public static string PackageManager_Title {
            get {
                return ResourceManager.GetString("PackageManager_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspace is disconnected or R session is not running..
        /// </summary>
        public static string PackageManager_TransportError {
            get {
                return ResourceManager.GetString("PackageManager_TransportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall this package.
        /// </summary>
        public static string PackageManager_UninstallButtonToolTip {
            get {
                return ResourceManager.GetString("PackageManager_UninstallButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unload {0}..
        /// </summary>
        public static string PackageManager_UnloadButtonToolTip {
            get {
                return ResourceManager.GetString("PackageManager_UnloadButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available.
        /// </summary>
        public static string PackageManager_UpdateAvailableToolTip {
            get {
                return ResourceManager.GetString("PackageManager_UpdateAvailableToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update {0} to version {1}.
        /// </summary>
        public static string PackageManager_UpdateButtonToolTip {
            get {
                return ResourceManager.GetString("PackageManager_UpdateButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical splitter.
        /// </summary>
        public static string PackageManager_VerticalSplitter {
            get {
                return ResourceManager.GetString("PackageManager_VerticalSplitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical Memory: {0} MB, {1} MB free.
        /// </summary>
        public static string PhysicalMemory {
            get {
                return ResourceManager.GetString("PhysicalMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run plotting command in R Interactive Window.
        /// </summary>
        public static string Plot_EmptyWatermark {
            get {
                return ResourceManager.GetString("Plot_EmptyWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot.
        /// </summary>
        public static string PlotHistory_AutomationName {
            get {
                return ResourceManager.GetString("PlotHistory_AutomationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot history is empty.
        /// </summary>
        public static string PlotHistory_EmptyWatermark {
            get {
                return ResourceManager.GetString("PlotHistory_EmptyWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error copying plot to the clipboard.\n{0}.
        /// </summary>
        public static string Plots_CopyToClipboardError {
            get {
                return ResourceManager.GetString("Plots_CopyToClipboardError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device {0}.
        /// </summary>
        public static string Plots_DeviceName {
            get {
                return ResourceManager.GetString("Plots_DeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        public static string Plots_EvalError {
            get {
                return ResourceManager.GetString("Plots_EvalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Plot As Image.
        /// </summary>
        public static string Plots_ExportAsImageDialogTitle {
            get {
                return ResourceManager.GetString("Plots_ExportAsImageDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG (*.png)|*.png|JPEG (*.jpg;*.jpeg)|*.jpg;*.jpeg|BMP (*.bmp)|*.bmp|TIFF (*.tif;*.tiff)|*.tif;*.tiff|All Files (*.*)|*.*.
        /// </summary>
        public static string Plots_ExportAsImageFilter {
            get {
                return ResourceManager.GetString("Plots_ExportAsImageFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Plot As PDF.
        /// </summary>
        public static string Plots_ExportAsPdfDialogTitle {
            get {
                return ResourceManager.GetString("Plots_ExportAsPdfDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF (*.pdf)|*.pdf|All Files (*.*)|*.*.
        /// </summary>
        public static string Plots_ExportAsPdfFilter {
            get {
                return ResourceManager.GetString("Plots_ExportAsPdfFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File extension &apos;{0}&apos; is not a supported image file format..
        /// </summary>
        public static string Plots_ExportUnsupportedImageFormat {
            get {
                return ResourceManager.GetString("Plots_ExportUnsupportedImageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove all plots from {0}?.
        /// </summary>
        public static string Plots_RemoveAllPlotsWarning {
            get {
                return ResourceManager.GetString("Plots_RemoveAllPlotsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the current plot from {0}?.
        /// </summary>
        public static string Plots_RemoveCurrentPlotWarning {
            get {
                return ResourceManager.GetString("Plots_RemoveCurrentPlotWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the selected plot?.
        /// </summary>
        public static string Plots_RemoveSelectedPlotWarning {
            get {
                return ResourceManager.GetString("Plots_RemoveSelectedPlotWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locator is active. Click in the plot window to select points then choose End Locator..
        /// </summary>
        public static string Plots_StatusLocatorActive {
            get {
                return ResourceManager.GetString("Plots_StatusLocatorActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to R host process failed..
        /// </summary>
        public static string Plots_TransportError {
            get {
                return ResourceManager.GetString("Plots_TransportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Plot - {0}.
        /// </summary>
        public static string Plots_WindowCaptionDevice {
            get {
                return ResourceManager.GetString("Plots_WindowCaptionDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Plot - {0} - Active.
        /// </summary>
        public static string Plots_WindowCaptionDeviceActive {
            get {
                return ResourceManager.GetString("Plots_WindowCaptionDeviceActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Plot - {0} - Locator is Active.
        /// </summary>
        public static string Plots_WindowCaptionLocatorActive {
            get {
                return ResourceManager.GetString("Plots_WindowCaptionLocatorActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Plot.
        /// </summary>
        public static string Plots_WindowCaptionNoDevice {
            get {
                return ResourceManager.GetString("Plots_WindowCaptionNoDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU Count: {0}.
        /// </summary>
        public static string ProcessorCount {
            get {
                return ResourceManager.GetString("ProcessorCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching file {0}....
        /// </summary>
        public static string Progress_FetchingFile {
            get {
                return ResourceManager.GetString("Progress_FetchingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Workspaces window and either select local R interpreter or try connecting to a remote machine..
        /// </summary>
        public static string ReconnectToBroker {
            get {
                return ResourceManager.GetString("ReconnectToBroker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote workspace &apos;{0}&apos; : {1}.
        /// </summary>
        public static string RemoteConnection {
            get {
                return ResourceManager.GetString("RemoteConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Interactive.
        /// </summary>
        public static string ReplWindowName {
            get {
                return ResourceManager.GetString("ReplWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &quot;Reset&quot; to start a new session..
        /// </summary>
        public static string RestartRHost {
            get {
                return ResourceManager.GetString("RestartRHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Services Information:.
        /// </summary>
        public static string RServices_Information {
            get {
                return ResourceManager.GetString("RServices_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autosaving workspace to image &apos;{0}&apos; ....
        /// </summary>
        public static string rtvs_AutosavingWorkspace {
            get {
                return ResourceManager.GetString("rtvs_AutosavingWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete autosaved workspace image &apos;{0}&apos;?.
        /// </summary>
        public static string rtvs_ConfirmDeleteWorkspace {
            get {
                return ResourceManager.GetString("rtvs_ConfirmDeleteWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting autosaved workspace image &apos;{0}&apos;..
        /// </summary>
        public static string rtvs_DeletingWorkspace {
            get {
                return ResourceManager.GetString("rtvs_DeletingWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load workspace from autosaved image &apos;{0}&apos;..
        /// </summary>
        public static string rtvs_FailedToLoadWorkspace {
            get {
                return ResourceManager.GetString("rtvs_FailedToLoadWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded workspace from autosaved image &apos;{0}&apos;..
        /// </summary>
        public static string rtvs_LoadedWorkspace {
            get {
                return ResourceManager.GetString("rtvs_LoadedWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous R session terminated, and its global workspace has been saved to image &apos;{0}&apos;. Would you like to reload it?.
        /// </summary>
        public static string rtvs_SessionTerminatedUnexpectedly {
            get {
                return ResourceManager.GetString("rtvs_SessionTerminatedUnexpectedly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  workspace saved successfully..
        /// </summary>
        public static string rtvs_WorkspaceSavedSuccessfully {
            get {
                return ResourceManager.GetString("rtvs_WorkspaceSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure.
        /// </summary>
        public static string SecureConnection {
            get {
                return ResourceManager.GetString("SecureConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to select specific R version, specify its id 
        ///number in the connection URL in the form &apos;https://remote:5444#2&apos;.
        /// </summary>
        public static string SelectInterpreterInstruction {
            get {
                return ResourceManager.GetString("SelectInterpreterInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # File content was generated on {0}..
        /// </summary>
        public static string SettingsFileGeneratedStamp {
            get {
                return ResourceManager.GetString("SettingsFileGeneratedStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Application settings file..
        /// </summary>
        public static string SettingsFileHeader {
            get {
                return ResourceManager.GetString("SettingsFileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string Uninstall {
            get {
                return ResourceManager.GetString("Uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Warning: UNTRUSTED].
        /// </summary>
        public static string UntrustedConnection {
            get {
                return ResourceManager.GetString("UntrustedConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video controller[{0}]: {1}.
        /// </summary>
        public static string VideoCardName {
            get {
                return ResourceManager.GetString("VideoCardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPU[{0}]: {1}.
        /// </summary>
        public static string VideoProcessor {
            get {
                return ResourceManager.GetString("VideoProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video memory[{0}]: {1} MB.
        /// </summary>
        public static string VideoRAM {
            get {
                return ResourceManager.GetString("VideoRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Memory: {0} MB, {1} MB free.
        /// </summary>
        public static string VirtualMemory {
            get {
                return ResourceManager.GetString("VirtualMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetting R session will clear the workspace. Would you like to save state?
        ///
        ///This prompt can be suppressed in R Tools | Options.
        ///    .
        /// </summary>
        public static string Warning_SaveOnReset {
            get {
                return ResourceManager.GetString("Warning_SaveOnReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminating R will immediately abort calculations and all workspace objects will be discarded. This action cannot be undone.
        ///
        ///Are you sure you want to terminate R session?.
        /// </summary>
        public static string Warning_TerminateR {
            get {
                return ResourceManager.GetString("Warning_TerminateR", resourceCulture);
            }
        }
    }
}
