//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.R.Editor {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.R.Editor.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic formatting.
        /// </summary>
        internal static string AutoFormat {
            get {
                return ResourceManager.GetString("AutoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment selection.
        /// </summary>
        internal static string CommentSelection {
            get {
                return ResourceManager.GetString("CommentSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ) expected.
        /// </summary>
        internal static string ParseError_CloseBraceExpected {
            get {
                return ResourceManager.GetString("ParseError_CloseBraceExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to } expected.
        /// </summary>
        internal static string ParseError_CloseCurlyBraceExpected {
            get {
                return ResourceManager.GetString("ParseError_CloseCurlyBraceExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ] or ]] expected.
        /// </summary>
        internal static string ParseError_CloseSquareBracketExpected {
            get {
                return ResourceManager.GetString("ParseError_CloseSquareBracketExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression expected.
        /// </summary>
        internal static string ParseError_ExpressionExpected {
            get {
                return ResourceManager.GetString("ParseError_ExpressionExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function body expected.
        /// </summary>
        internal static string ParseError_FunctionBodyExpected {
            get {
                return ResourceManager.GetString("ParseError_FunctionBodyExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function expected.
        /// </summary>
        internal static string ParseError_FunctionExpected {
            get {
                return ResourceManager.GetString("ParseError_FunctionExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error.
        /// </summary>
        internal static string ParseError_General {
            get {
                return ResourceManager.GetString("ParseError_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier expected.
        /// </summary>
        internal static string ParseError_IndentifierExpected {
            get {
                return ResourceManager.GetString("ParseError_IndentifierExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;in&apos; expected.
        /// </summary>
        internal static string ParseError_InKeywordExpected {
            get {
                return ResourceManager.GetString("ParseError_InKeywordExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operand to the left expected.
        /// </summary>
        internal static string ParseError_LeftOperandExpected {
            get {
                return ResourceManager.GetString("ParseError_LeftOperandExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logical expected.
        /// </summary>
        internal static string ParseError_LogicalExpected {
            get {
                return ResourceManager.GetString("ParseError_LogicalExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number expected.
        /// </summary>
        internal static string ParseError_NumberExpected {
            get {
                return ResourceManager.GetString("ParseError_NumberExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ( expected.
        /// </summary>
        internal static string ParseError_OpenBraceExpected {
            get {
                return ResourceManager.GetString("ParseError_OpenBraceExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to { expected.
        /// </summary>
        internal static string ParseError_OpenCurlyBraceExpected {
            get {
                return ResourceManager.GetString("ParseError_OpenCurlyBraceExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ or [[ expected.
        /// </summary>
        internal static string ParseError_OpenSquareBracketExpected {
            get {
                return ResourceManager.GetString("ParseError_OpenSquareBracketExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator expected.
        /// </summary>
        internal static string ParseError_OperatorExpected {
            get {
                return ResourceManager.GetString("ParseError_OperatorExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operand to the right expected.
        /// </summary>
        internal static string ParseError_RightOperandExpected {
            get {
                return ResourceManager.GetString("ParseError_RightOperandExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String expected.
        /// </summary>
        internal static string ParseError_StringExpected {
            get {
                return ResourceManager.GetString("ParseError_StringExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of file.
        /// </summary>
        internal static string ParseError_UnexpectedEndOfFile {
            get {
                return ResourceManager.GetString("ParseError_UnexpectedEndOfFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected token.
        /// </summary>
        internal static string ParseError_UnexpectedToken {
            get {
                return ResourceManager.GetString("ParseError_UnexpectedToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncomment selection.
        /// </summary>
        internal static string UncommentSelection {
            get {
                return ResourceManager.GetString("UncommentSelection", resourceCulture);
            }
        }
    }
}
