///////////////////////////////////////////////////////////////////////////////
//
// ShellIcons.h
// Do not tamper with the order of the items below!
//
// If you want to add new items to the ShellIcons.png strip here are the steps.
//
// 1:  Look for an //UNUSED tag indicating there is a 'slot' in the existing
//     strip that is empty.  If you find one replace the text UNUSED with an 
//     image id (like cmdidVsShellMyCoolImage) and uncomment the line.
//
// 2:  If there is no UNUSED tag available then simply add your id to the end of
//     the list using the next sequential number.
//
// 3:  Finally, you want to insert your image into the ShellIcons.png strip at 
//     X-offset (id - 1)*16.
//
///////////////////////////////////////////////////////////////////////////////

#ifndef __SHELLICONS_H__
#define __SHELLICONS_H__

#define cmdidVsShellUser                                        32768   // app-custom controls should use tcid >= cmdidVsShellUser
#define cmdidVsShellInteractiveSessionInterrupt                     1   // Cancel evaluation in interactive window
#define cmdidVsShellInteractiveSessionRestart                       2   // Reset interactive window session
#define cmdidVsShellAlignObjectsBottom                              3   // AlignObjectsBottom,
#define cmdidVsShellAlignObjectsCenteredHorizontal                  4   // AlignObjectsCenteredHorizontal,
#define cmdidVsShellAlignObjectsCenteredVertical                    5   // AlignObjectsCenteredVertical,
#define cmdidVsShellAlignObjectsLeft                                6   // AlignObjectsLeft,
#define cmdidVsShellAlignObjectsRight                               7   // AlignObjectsRight,
#define cmdidVsShellAlignObjectsTop                                 8   // AlignObjectsTop,
#define cmdidVsShellAlignToGrid                                     9   // AlignToGrid,
#define cmdidVsShellBold                                           10   // Bold,
#define cmdidVsShellBringToFront                                   11   // BringToFront,
#define cmdidVsShellBullets                                        12   // Bullets,
#define cmdidVsShellCascadeWindows                                 13   // CascadeWindows,
#define cmdidVsShellCentered                                       14   // Centered,
#define cmdidVsShellCenterHorizontallyInForm                       15   // CenterHorizontallyInForm,
#define cmdidVsShellCenterVerticallyInForm                         16   // CenterVerticallyInForm,
#define cmdidVsShellClear                                          17   // Clear,
#define cmdidVsShellClose                                          18   // Close,
#define cmdidVsShellCodeWindow                                     19   // CodeWindow,
#define cmdidVsShellCollapse2                                      20   // Collapse2,
#define cmdidVsShellColumns                                        21   // Columns,
#define cmdidVsShellCompleteWord                                   22   // CompleteWord,
#define cmdidVsShellCopy                                           23   // Copy,
#define cmdidVsShellFont                                           24   // Font,
#define cmdidVsShellCut                                            25   // Cut,
#define cmdidVsShellDeclineInvitation                              26   // DeclineInvitation,
#define cmdidVsShellDelete                                         27   // Delete,
#define cmdidVsShellDeleteAllInkAnnots                             28   // DeleteAllInkAnnots,
#define cmdidVsShellDeleteCells                                    29   // DeleteCells,
#define cmdidVsShellDeleteColumns                                  30   // DeleteColumns,
#define cmdidVsShellDeleteRows                                     31   // DeleteRows,
#define cmdidVsShellDownArrow                                      32   // DownArrow,
#define cmdidVsShellExit                                           33   // Exit,
#define cmdidVsShellExpand2                                        34   // Expand2,
#define cmdidVsShellF1Help                                         35   // F1Help,
#define cmdidVsShellFieldList                                      36   // FieldList,
#define cmdidVsShellFind                                           37   // Find,
#define cmdidVsShellFullJustify                                    38   // FullJustify,
#define cmdidVsShellFullScreen                                     39   // FullScreen,
#define cmdidVsShellGraph                                          40   // Graph,
#define cmdidVsShellHappyFace                                      41   // HappyFace,
#define cmdidVsShellFilter                                         42   // Filter
#define cmdidVsShellHideWindow                                     43   // HideWindow,
#define cmdidVsShellHorizontalSpacingDecrease                      44   // HorizontalSpacingDecrease,
#define cmdidVsShellHorizontalSpacingIncrease                      45   // HorizontalSpacingIncrease,
#define cmdidVsShellHorizontalSpacingMakeEqual                     46   // HorizontalSpacingMakeEqual,
#define cmdidVsShellHorizontalSpacingRemove                        47   // HorizontalSpacingRemove,
#define cmdidVsShellIndent                                         48   // Indent,
#define cmdidVsShellIndentRTL                                      49   // IndentRTL,
#define cmdidVsShellIndentVerticalBT                               50   // IndentVerticalBT,
#define cmdidVsShellInsertCells                                    51   // InsertCells,
#define cmdidVsShellInsertColumnsLeft                              52   // InsertColumnsLeft,
#define cmdidVsShellInsertColumnsRight                             53   // InsertColumnsRight,
#define cmdidVsShellInsertRowsAbove                                54   // InsertRowsAbove,
#define cmdidVsShellInsertRowsBelow                                55   // InsertRowsBelow,
#define cmdidVsShellInsertTable                                    56   // InsertTable,
#define cmdidVsShellItalic                                         57   // Italic,
#define cmdidVsShellLeftArrow                                      58   // LeftArrow,
#define cmdidVsShellLeftJustify                                    59   // LeftJustify,
#define cmdidVsShellLineChart                                      60   // LineChart,
#define cmdidVsShellMergeCells                                     61   // MergeCells,
#define cmdidVsShellSplitCells                                     62   // SplitCells,
#define cmdidVsShellNewFolder                                      63   // NewFolder,
#define cmdidVsShellNewTask                                        64   // NewTask,
//#define UNUSED                                                   65   // Not Used, if replaced put your icon description here
#define cmdidVsShellNumbering                                      66   // Numbering,
//#define UNUSED                                                   67   // Not Used, if replaced put your icon description here
#define cmdidVsShellOpen                                           68   // Open,
#define cmdidVsShellOptions                                        69   // Options,
#define cmdidVsShellOutdent                                        70   // Outdent,
#define cmdidVsShellOutlineView                                    71   // OutlineView,
#define cmdidVsShellParagraphDialog                                72   // ParagraphDialog,
#define cmdidVsShellParameterInfo                                  73   // ParameterInfo,
#define cmdidVsShellPaste                                          74   // Paste,
#define cmdidVsShellPause                                          75   // Pause,
#define cmdidVsShellPlay                                           76   // Play,
#define cmdidVsShellPrint                                          77   // Print,
#define cmdidVsShellPrintPreview                                   78   // PrintPreview,
#define cmdidVsShellPrintSetup                                     79   // PrintSetup,
#define cmdidVsShellProperties                                     80   // Properties,
#define cmdidVsShellPSSHelp                                        81   // PSSHelp,
#define cmdidVsShellQuickInfo                                      82   // QuickInfo,
#define cmdidVsShellReports                                        83   // Reports
#define cmdidVsShellRecord                                         84   // Record,
#define cmdidVsShellRedo                                           85   // Redo,
#define cmdidVsShellREM                                            86   // REM,
#define cmdidVsShellRename                                         87   // Rename,
#define cmdidVsShellRenameFolder                                   88   // RenameFolder,
#define cmdidVsShellRenameMaster                                   89   // RenameMaster,
#define cmdidVsShellRestart                                        90   // Restart,
#define cmdidVsShellRightArrow                                     91   // RightArrow,
#define cmdidVsShellRightJustify                                   92   // RightJustify,
#define cmdidVsShellRotateLeft                                     93   // RotateLeft,
#define cmdidVsShellRotateRight                                    94   // RotateRight,
#define cmdidVsShellSave                                           95   // Save,
#define cmdidVsShellSaveAll                                        96   // SaveAll,
#define cmdidVsShellSelectAll                                      97   // SelectAll,
#define cmdidVsShellSelectMember                                   98   // SelectMember,
#define cmdidVsShellSendToBack                                     99   // SendToBack,
#define cmdidVsShellSetNextStatement                              100   // SetNextStatement,
#define cmdidVsShellShowNextStatement                             101   // ShowNextStatement,
#define cmdidVsShellSizeToControlHeight                           102   // SizeToControlHeight,
#define cmdidVsShellSizeToControlHeightAndWidth                   103   // SizeToControlHeightAndWidth,
#define cmdidVsShellSizeToControlWidth                            104   // SizeToControlWidth,
#define cmdidVsShellSizeToGrid                                    105   // SizeToGrid,
#define cmdidVsShellFormatDrawingObject                           106   // FormatDrawingObject,
#define cmdidVsShellSortingGrouping                               107   // SortingGrouping,
#define cmdidVsShellSortUp                                        108   // SortUp,
#define cmdidVsShellSplit                                         109   // Split,
#define cmdidVsShellDistributeColumn                              110   // DistributeColumn,
#define cmdidVsShellDistributeRow                                 111   // DistributeRow,
#define cmdidVsShellStepIn                                        112   // StepIn,
#define cmdidVsShellStepOut                                       113   // StepOut,
#define cmdidVsShellStepOver                                      114   // StepOver,
#define cmdidVsShellStepToCursor                                  115   // StepToCursor,
#define cmdidVsShellStop                                          116   // Stop,
#define cmdidVsShellSubscript                                     117   // Subscript,
#define cmdidVsShellSuperscript                                   118   // Superscript,
#define cmdidVsShellTabOrder                                      119   // TabOrder,
#define cmdidVsShellTileWindowsHorizontally                       120   // TileWindowsHorizontally,
#define cmdidVsShellTileWindowsVertically                         121   // TileWindowsVertically,
#define cmdidVsShellToolbox                                       122   // Toolbox,
#define cmdidVsShellToolLock                                      123   // ToolLock,
#define cmdidVsShellUnderline                                     124   // Underline,
#define cmdidVsShellUndo                                          125   // Undo,
#define cmdidVsShellUnREM                                         126   // UnREM,
#define cmdidVsShellUpArrow                                       127   // UpArrow,
#define cmdidVsShellVBProjectProperties                           128   // VBProjectProperties,
#define cmdidVsShellVerticalSpacingDecrease                       129   // VerticalSpacingDecrease,
#define cmdidVsShellVerticalSpacingIncrease                       130   // VerticalSpacingIncrease,
#define cmdidVsShellVerticalSpacingMakeEqual                      131   // VerticalSpacingMakeEqual,
#define cmdidVsShellVerticalSpacingRemove                         132   // VerticalSpacingRemove,
#define cmdidVsShellViewPropertyPages                             133   // ViewPropertyPages,
#define cmdidVsShellViewVBEObject                                 134   // ViewVBEObject,
#define cmdidVsShellWebStopLoading                                135   // WebStopLoading,
//#define UNUSED                                                  136   // Not Used, if replaced put your icon description here
#define cmdidVsShellZoom                                          137   // Zoom,
#define cmdidVsShellZoomIn                                        138   // ZoomIn,
#define cmdidVsShellZoomOut                                       139   // ZoomOut,
#define cmdidVsShellPinTab                                        140   // PinTab,
#define cmdidVsShellPromoteTab                                    141   // PromoteTab,
#define cmdidVsShellBringFloatingWindowsToFront                   142   // BringFloatingWindowsToFront,
#define cmdidVsShellStartupSettings                               143   // StartupSettings,
#define cmdidVsShellNil                                           144   // Nil,
#define cmdidVsShellSortDialog                                    145   // SortDialog,
#define cmdidVsShellWatch                                         146   // Watch,
#define cmdidVsShellDeleteWatch                                   147   // DeleteWatch,
#define cmdidVsShellImmediateWindow                               148   // ImmediateWindow,
#define cmdidVsShellCollapseParent                                149   // CollapseParent
#endif //__SHELLICONS_H__
