#!/usr/bin/env bash

if [ -z "$1" ]; then
    dotnet /usr/lib/rtvs/Microsoft.R.Host.Broker.Linux.dll --config /etc/rtvs/Microsoft.R.Host.Broker.Config.json
else
    dotnet /usr/lib/rtvs/Microsoft.R.Host.Broker.Linux.dll --config $1
fi
