#!/usr/bin/env bash

if [ -z "$1" ]; then
    dotnet /usr/lib/rtvs/Microsoft.R.Host.Broker.Unix.dll --config /etc/rtvs/rtvsd.config.json
else
    dotnet /usr/lib/rtvs/Microsoft.R.Host.Broker.Unix.dll --config $1
fi
