//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.R.Host.Broker {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.R.Host.Broker.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load SSL Certificate: {0}.
        /// </summary>
        internal static string Critical_CertificateLoadFailed {
            get {
                return ResourceManager.GetString("Critical_CertificateLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested to write &apos;urls&apos; to pipe &apos;{0}&apos;, but it is not a valid pipe handle.
        /// </summary>
        internal static string Critical_InvalidPipeHandle {
            get {
                return ResourceManager.GetString("Critical_InvalidPipeHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TLS certificate not found: {0}.
        /// </summary>
        internal static string Critical_NoTlsCertificate {
            get {
                return ResourceManager.GetString("Critical_NoTlsCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designated parent process {0} not found.
        /// </summary>
        internal static string Critical_ParentProcessNotFound {
            get {
                return ResourceManager.GetString("Critical_ParentProcessNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping timed out, terminating.
        /// </summary>
        internal static string Critical_PingTimeOut {
            get {
                return ResourceManager.GetString("Critical_PingTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested to write &apos;urls&apos; to pipe &apos;{0}&apos;, but timed out while trying to connect to pipe.
        /// </summary>
        internal static string Critical_PipeConnectTimeOut {
            get {
                return ResourceManager.GetString("Critical_PipeConnectTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timed out waiting for graceful shutdown.
        /// </summary>
        internal static string Critical_TimeOutShutdown {
            get {
                return ResourceManager.GetString("Critical_TimeOutShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find session with id: {0}.
        /// </summary>
        internal static string Debug_SessionNotFound {
            get {
                return ResourceManager.GetString("Debug_SessionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} session creation blocked due to pending profile deletion..
        /// </summary>
        internal static string Error_BlockedByProfileDeletion {
            get {
                return ResourceManager.GetString("Error_BlockedByProfileDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client disconnected from R session due to error: {0}.
        /// </summary>
        internal static string Error_ClientToHostConnectionFailed {
            get {
                return ResourceManager.GetString("Error_ClientToHostConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config file load failed: {0}.
        /// </summary>
        internal static string Error_ConfigLoadFailed {
            get {
                return ResourceManager.GetString("Error_ConfigLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config file parse failed: {0}.
        /// </summary>
        internal static string Error_ConfigParseFailed {
            get {
                return ResourceManager.GetString("Error_ConfigParseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server port {0} is already in use..
        /// </summary>
        internal static string Error_ConfiguredPortNotAvailable {
            get {
                return ResourceManager.GetString("Error_ConfiguredPortNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Host exited with error : {0}.
        /// </summary>
        internal static string Error_ExitRHost {
            get {
                return ResourceManager.GetString("Error_ExitRHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve R installation data for interpreter \&quot;{0}\&quot; at \&quot;{1}\&quot;.
        /// </summary>
        internal static string Error_FailedRInstallationData {
            get {
                return ResourceManager.GetString("Error_FailedRInstallationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client failed to disconnect gracefully: {0}.
        /// </summary>
        internal static string Error_GracefulDisconnectFailed {
            get {
                return ResourceManager.GetString("Error_GracefulDisconnectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R session disconnected from client due to error: {0}.
        /// </summary>
        internal static string Error_HostToClientConnectionFailed {
            get {
                return ResourceManager.GetString("Error_HostToClientConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No compatible R interpreters found.
        /// </summary>
        internal static string Error_NoRInterpreters {
            get {
                return ResourceManager.GetString("Error_NoRInterpreters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R session process failed to start. Error: {0}.
        /// </summary>
        internal static string Error_RHostFailedToStart {
            get {
                return ResourceManager.GetString("Error_RHostFailedToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve certificate for encryption. Exception: {0}..
        /// </summary>
        internal static string Error_UnableToGetCertificateForEncryption {
            get {
                return ResourceManager.GetString("Error_UnableToGetCertificateForEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipe already has a client end.
        /// </summary>
        internal static string Exception_PipeHasClientEnd {
            get {
                return ResourceManager.GetString("Exception_PipeHasClientEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipe already has a host end.
        /// </summary>
        internal static string Exception_PipeHasHostEnd {
            get {
                return ResourceManager.GetString("Exception_PipeHasHostEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring parent process {0}.
        /// </summary>
        internal static string Info_MonitoringParentProcess {
            get {
                return ResourceManager.GetString("Info_MonitoringParentProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent process {0} exited, shutting down.
        /// </summary>
        internal static string Info_ParentProcessExited {
            get {
                return ResourceManager.GetString("Info_ParentProcessExited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R session started for connection {0} of user {1}.
        /// </summary>
        internal static string Info_StartedRHost {
            get {
                return ResourceManager.GetString("Info_StartedRHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting R session for connection {0} of user {1} with command line: {2}.
        /// </summary>
        internal static string Info_StartingRHost {
            get {
                return ResourceManager.GetString("Info_StartingRHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-detecting R ....
        /// </summary>
        internal static string Trace_AutoDetectingR {
            get {
                return ResourceManager.GetString("Trace_AutoDetectingR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate issued by {0}.
        /// </summary>
        internal static string Trace_CertificateIssuer {
            get {
                return ResourceManager.GetString("Trace_CertificateIssuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate issued to {0}.
        /// </summary>
        internal static string Trace_CertificateSubject {
            get {
                return ResourceManager.GetString("Trace_CertificateSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R {0} detected at \&quot;{1}\&quot;.
        /// </summary>
        internal static string Trace_DetectedR {
            get {
                return ResourceManager.GetString("Trace_DetectedR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |{0}|: {1}.
        /// </summary>
        internal static string Trace_ErrorDataReceived {
            get {
                return ResourceManager.GetString("Trace_ErrorDataReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing &apos;urls&apos; to pipe &apos;{0}&apos;:{1}{2}.
        /// </summary>
        internal static string Trace_ServerUrlsToPipeBegin {
            get {
                return ResourceManager.GetString("Trace_ServerUrlsToPipeBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrote &apos;urls&apos; to pipe &apos;{0}&apos;.
        /// </summary>
        internal static string Trace_ServerUrlsToPipeDone {
            get {
                return ResourceManager.GetString("Trace_ServerUrlsToPipeDone", resourceCulture);
            }
        }
    }
}
