//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Common.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Common.Core.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 x 6 in..
        /// </summary>
        internal static string Combobox_4x6inches {
            get {
                return ResourceManager.GetString("Combobox_4x6inches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 x 7 in..
        /// </summary>
        internal static string Combobox_5x7inches {
            get {
                return ResourceManager.GetString("Combobox_5x7inches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 x 8 in..
        /// </summary>
        internal static string Combobox_6x8inches {
            get {
                return ResourceManager.GetString("Combobox_6x8inches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A4.
        /// </summary>
        internal static string Combobox_A4 {
            get {
                return ResourceManager.GetString("Combobox_A4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A5.
        /// </summary>
        internal static string Combobox_A5 {
            get {
                return ResourceManager.GetString("Combobox_A5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A6.
        /// </summary>
        internal static string Combobox_A6 {
            get {
                return ResourceManager.GetString("Combobox_A6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string Combobox_Custom {
            get {
                return ResourceManager.GetString("Combobox_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Size.
        /// </summary>
        internal static string Combobox_DeviceSize {
            get {
                return ResourceManager.GetString("Combobox_DeviceSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Executive.
        /// </summary>
        internal static string Combobox_USExecutive {
            get {
                return ResourceManager.GetString("Combobox_USExecutive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Legal.
        /// </summary>
        internal static string Combobox_UsLegal {
            get {
                return ResourceManager.GetString("Combobox_UsLegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Letter.
        /// </summary>
        internal static string Combobox_UsLetter {
            get {
                return ResourceManager.GetString("Combobox_UsLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credential handle is invalid..
        /// </summary>
        internal static string Error_CredentialHandleInvalid {
            get {
                return ResourceManager.GetString("Error_CredentialHandleInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading credentails failed with Win32 error..
        /// </summary>
        internal static string Error_CredReadFailed {
            get {
                return ResourceManager.GetString("Error_CredReadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing credentails failed with Win32 error..
        /// </summary>
        internal static string Error_CredWriteFailed {
            get {
                return ResourceManager.GetString("Error_CredWriteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to {0}.
        /// </summary>
        internal static string Info_ConnectingTo {
            get {
                return ResourceManager.GetString("Info_ConnectingTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Tools for Visual Studio.
        /// </summary>
        internal static string MessageBoxTitle {
            get {
                return ResourceManager.GetString("MessageBoxTitle", resourceCulture);
            }
        }
    }
}
