//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Markdown.Editor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Markdown.Editor.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected exception occurred.
        /// </summary>
        internal static string BrowserView_Error {
            get {
                return ResourceManager.GetString("BrowserView_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown Alt Text.
        /// </summary>
        internal static string ColorName_MD_AltText {
            get {
                return ResourceManager.GetString("ColorName_MD_AltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown Blockquote.
        /// </summary>
        internal static string ColorName_MD_Blockquote {
            get {
                return ResourceManager.GetString("ColorName_MD_Blockquote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown Bold Text.
        /// </summary>
        internal static string ColorName_MD_Bold {
            get {
                return ResourceManager.GetString("ColorName_MD_Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown Bold Italic Text.
        /// </summary>
        internal static string ColorName_MD_BoldItalic {
            get {
                return ResourceManager.GetString("ColorName_MD_BoldItalic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown Code Block.
        /// </summary>
        internal static string ColorName_MD_Code {
            get {
                return ResourceManager.GetString("ColorName_MD_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown Code Background.
        /// </summary>
        internal static string ColorName_MD_CodeBackground {
            get {
                return ResourceManager.GetString("ColorName_MD_CodeBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown Heading.
        /// </summary>
        internal static string ColorName_MD_Heading {
            get {
                return ResourceManager.GetString("ColorName_MD_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown Italic Text.
        /// </summary>
        internal static string ColorName_MD_Italic {
            get {
                return ResourceManager.GetString("ColorName_MD_Italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown List Item.
        /// </summary>
        internal static string ColorName_MD_ListItem {
            get {
                return ResourceManager.GetString("ColorName_MD_ListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown Monospace Text.
        /// </summary>
        internal static string ColorName_MD_Monospace {
            get {
                return ResourceManager.GetString("ColorName_MD_Monospace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll sync is active.
        /// </summary>
        internal static string ScrollSync_Active {
            get {
                return ResourceManager.GetString("ScrollSync_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll sync is paused.
        /// </summary>
        internal static string ScrollSync_Paused {
            get {
                return ResourceManager.GetString("ScrollSync_Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to toggle scroll sync.
        /// </summary>
        internal static string ScrollSync_Tooltip {
            get {
                return ResourceManager.GetString("ScrollSync_Tooltip", resourceCulture);
            }
        }
    }
}
