//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Markdown.Editor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Markdown.Editor.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause automatic view synchronization.
        /// </summary>
        public static string AutomaticSyncPauseTooltip {
            get {
                return ResourceManager.GetString("AutomaticSyncPauseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate automatic view synchronization.
        /// </summary>
        public static string AutomaticSyncPlayTooltip {
            get {
                return ResourceManager.GetString("AutomaticSyncPlayTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected exception occurred.
        /// </summary>
        public static string BrowserView_Error {
            get {
                return ResourceManager.GetString("BrowserView_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown Alt Text.
        /// </summary>
        public static string ColorName_MD_AltText {
            get {
                return ResourceManager.GetString("ColorName_MD_AltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown Blockquote.
        /// </summary>
        public static string ColorName_MD_Blockquote {
            get {
                return ResourceManager.GetString("ColorName_MD_Blockquote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown Bold Text.
        /// </summary>
        public static string ColorName_MD_Bold {
            get {
                return ResourceManager.GetString("ColorName_MD_Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown Bold Italic Text.
        /// </summary>
        public static string ColorName_MD_BoldItalic {
            get {
                return ResourceManager.GetString("ColorName_MD_BoldItalic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown Code Block.
        /// </summary>
        public static string ColorName_MD_Code {
            get {
                return ResourceManager.GetString("ColorName_MD_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown Code Background.
        /// </summary>
        public static string ColorName_MD_CodeBackground {
            get {
                return ResourceManager.GetString("ColorName_MD_CodeBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown Heading.
        /// </summary>
        public static string ColorName_MD_Heading {
            get {
                return ResourceManager.GetString("ColorName_MD_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown Italic Text.
        /// </summary>
        public static string ColorName_MD_Italic {
            get {
                return ResourceManager.GetString("ColorName_MD_Italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown List Item.
        /// </summary>
        public static string ColorName_MD_ListItem {
            get {
                return ResourceManager.GetString("ColorName_MD_ListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown Monospace Text.
        /// </summary>
        public static string ColorName_MD_Monospace {
            get {
                return ResourceManager.GetString("ColorName_MD_Monospace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation requires package {0} which is not installed or has been removed. .
        /// </summary>
        public static string Error_PackageMissing {
            get {
                return ResourceManager.GetString("Error_PackageMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing markdown requires Pandoc. Please install Pandoc for Windows from http://pandoc.org/installing.html.
        ///    
        ///Click OK to open the Pandoc download page in default browser. You may need to restart Visual Studio when the Pandoc setup completes..
        /// </summary>
        public static string Error_PandocMissingLocal {
            get {
                return ResourceManager.GetString("Error_PandocMissingLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing markdown requires Pandoc. Please contact the remote machine administrator and ask them to install Pandoc for Windows from http://pandoc.org/installing.html.
        ///    
        ///Click OK to open the Pandoc download page in default browser. R Remote Services process may need to be restarted when the Pandoc setup completes..
        /// </summary>
        public static string Error_PandocMissingRemote {
            get {
                return ResourceManager.GetString("Error_PandocMissingRemote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing markdown to PDF requires TeX installation. Please install MiKTeX (Complete) from http://miktex.org/2.9/setup. Be sure to download the Complete installation.
        ///    
        ///Click OK to open MiKTeX download page in the default browser. You may need to restart Visual Studio when the MiKTeX setup completes.
        ///.
        /// </summary>
        public static string Error_PdfLatexMissingLocal {
            get {
                return ResourceManager.GetString("Error_PdfLatexMissingLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing markdown to PDF requires TeX installation. Please contact the remote machine administrator and ask them to install MiKTeX (Complete) from http://miktex.org/2.9/setup. Be sure to download the Complete installation.
        ///
        ///Click OK to open MiKTeX download page in the default browser. R Remote Services process may need to be restarted when the MiKTeX setup completes.
        ///.
        /// </summary>
        public static string Error_PdfLatexMissingRemote {
            get {
                return ResourceManager.GetString("Error_PdfLatexMissingRemote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving published output file: {0}.
        /// </summary>
        public static string Info_MarkdownGetOutputFile {
            get {
                return ResourceManager.GetString("Info_MarkdownGetOutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished publishing markdown file: {0}.
        /// </summary>
        public static string Info_MarkdownPublishComplete {
            get {
                return ResourceManager.GetString("Info_MarkdownPublishComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing markdown file: {0}.
        /// </summary>
        public static string Info_MarkdownPublishingFile {
            get {
                return ResourceManager.GetString("Info_MarkdownPublishingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending markdown input file to R: {0}.
        /// </summary>
        public static string Info_MarkdownSendingInputFile {
            get {
                return ResourceManager.GetString("Info_MarkdownSendingInputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Loading {
            get {
                object obj = ResourceManager.GetObject("Loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update HTML view.
        /// </summary>
        public static string ManualUpdateTooltip {
            get {
                return ResourceManager.GetString("ManualUpdateTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Code Chunk Output.
        /// </summary>
        public static string OutputPlaceholder {
            get {
                return ResourceManager.GetString("OutputPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knit and preview HTML.
        /// </summary>
        public static string PreviewHtmlTooltip {
            get {
                return ResourceManager.GetString("PreviewHtmlTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knit and preview PDF file.
        /// </summary>
        public static string PreviewPdfTooltip {
            get {
                return ResourceManager.GetString("PreviewPdfTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knit and preview Word file.
        /// </summary>
        public static string PreviewWordTooltip {
            get {
                return ResourceManager.GetString("PreviewWordTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run all chunks above.
        /// </summary>
        public static string SuggestedAction_RunAllChunksAbove {
            get {
                return ResourceManager.GetString("SuggestedAction_RunAllChunksAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run current chunk.
        /// </summary>
        public static string SuggestedAction_RunCurrentChunk {
            get {
                return ResourceManager.GetString("SuggestedAction_RunCurrentChunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current file cannot be saved in the current encoding. Do you want to save file in UTF-8 and continue?.
        /// </summary>
        public static string Warning_SaveInUtf8 {
            get {
                return ResourceManager.GetString("Warning_SaveInUtf8", resourceCulture);
            }
        }
    }
}
