//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.R.Editor.Windows {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Windows_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Windows_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.R.Editor.Windows.Resources", typeof(Windows_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Assignment.
        /// </summary>
        internal static string ColorName_R_Assignment {
            get {
                return ResourceManager.GetString("ColorName_R_Assignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Braces.
        /// </summary>
        internal static string ColorName_R_Braces {
            get {
                return ResourceManager.GetString("ColorName_R_Braces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Square Brackets.
        /// </summary>
        internal static string ColorName_R_Brackets {
            get {
                return ResourceManager.GetString("ColorName_R_Brackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Builtin Function.
        /// </summary>
        internal static string ColorName_R_Builtin {
            get {
                return ResourceManager.GetString("ColorName_R_Builtin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Comment.
        /// </summary>
        internal static string ColorName_R_Comment {
            get {
                return ResourceManager.GetString("ColorName_R_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Curly Brace.
        /// </summary>
        internal static string ColorName_R_CurlyBrace {
            get {
                return ResourceManager.GetString("ColorName_R_CurlyBrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Curly Braces.
        /// </summary>
        internal static string ColorName_R_CurlyBraces {
            get {
                return ResourceManager.GetString("ColorName_R_CurlyBraces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Function Default Parameter.
        /// </summary>
        internal static string ColorName_R_FunctionDefaultParameter {
            get {
                return ResourceManager.GetString("ColorName_R_FunctionDefaultParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Function Reference.
        /// </summary>
        internal static string ColorName_R_FunctionReference {
            get {
                return ResourceManager.GetString("ColorName_R_FunctionReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Keyword.
        /// </summary>
        internal static string ColorName_R_Keyword {
            get {
                return ResourceManager.GetString("ColorName_R_Keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Number.
        /// </summary>
        internal static string ColorName_R_Number {
            get {
                return ResourceManager.GetString("ColorName_R_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Operator.
        /// </summary>
        internal static string ColorName_R_Operator {
            get {
                return ResourceManager.GetString("ColorName_R_Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Punctuation.
        /// </summary>
        internal static string ColorName_R_Punctuation {
            get {
                return ResourceManager.GetString("ColorName_R_Punctuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roxygen Export.
        /// </summary>
        internal static string ColorName_R_RoxygenExport {
            get {
                return ResourceManager.GetString("ColorName_R_RoxygenExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roxygen Keyword.
        /// </summary>
        internal static string ColorName_R_RoxygenKeyword {
            get {
                return ResourceManager.GetString("ColorName_R_RoxygenKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R String.
        /// </summary>
        internal static string ColorName_R_String {
            get {
                return ResourceManager.GetString("ColorName_R_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Type Functions.
        /// </summary>
        internal static string ColorName_R_TypeFunction {
            get {
                return ResourceManager.GetString("ColorName_R_TypeFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RD Argument.
        /// </summary>
        internal static string ColorName_RD_Argument {
            get {
                return ResourceManager.GetString("ColorName_RD_Argument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RD Braces.
        /// </summary>
        internal static string ColorName_RD_CurlyBraces {
            get {
                return ResourceManager.GetString("ColorName_RD_CurlyBraces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag/drop.
        /// </summary>
        internal static string DragDropOperation {
            get {
                return ResourceManager.GetString("DragDropOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format document.
        /// </summary>
        internal static string FormatDocument {
            get {
                return ResourceManager.GetString("FormatDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interactive Window.
        /// </summary>
        internal static string ReplWindowName {
            get {
                return ResourceManager.GetString("ReplWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install package.
        /// </summary>
        internal static string SmartTagName_InstallPackage {
            get {
                return ResourceManager.GetString("SmartTagName_InstallPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load library.
        /// </summary>
        internal static string SmartTagName_LoadLibrary {
            get {
                return ResourceManager.GetString("SmartTagName_LoadLibrary", resourceCulture);
            }
        }
    }
}
